### PR TITLE
fix(scroll-assist): re-run when keyboard changes

### LINKED ISSUE #22940: bug: scroll assist does not re-run when changing keyboards
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
On iOS14 keyboard height changes when selecting Emojis, this causes ion-input field to be hidden by keyboard. Switching back from Emoji to ABC shows input field again as keyboard height again decreases.

**Expected behavior:**
Input field should always show above keyboard, not behind.

**Steps to reproduce:**

**Related code:**

html
```
<ion-content>
  <div class="backdrop_container"  (click)="goBack()"></div>
</ion-content>

<ion-footer>
  <ion-list lines="none">
    <ion-item>
      <ion-input [(ngModel)]="message" type="text" placeholder="{{'COMMENT.saysomething_pl | translate'}}"></ion-input>
      <ion-button (click)="submit()">
          <img src="../../../assets/icon/chat-send.svg" width="25px"/>
      </ion-button> 
    </ion-item>
  </ion-list>
</ion-footer>
```

scss
```
ion-content{
    --background: transparent;
 
    .backdrop_container{
        display: flex;
        flex: 1;
        width: 100%;
        height: 100%;
    }
    
}

ion-footer {
    ion-input{
        height: 40px !important;
    }

    ion-button{
        width: 45px !important;
        height: 45px !important;
        padding: 0;
        --background: var(--ion-color-green);
        --border-radius: 25px;
        margin-left: 10px;
        display: flex;
        justify-content: center;
        align-items: center;
    }
}
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.12.4 (/Users/xxx/.nvm/versions/node/v14.15.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.5.4
   @angular-devkit/build-angular : 0.901.14
   @angular-devkit/schematics    : 9.1.14
   @angular/cli                  : 9.1.14
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : ios 6.2.0
   Cordova Plugins   : cordova-plugin-ionic-webview 5.0.0, (and 11 other plugins)

Utility:

   cordova-res (update available: 0.15.3) : 0.15.2
   native-run                             : 1.3.0

System:

   ios-sim : 8.0.2
   NodeJS  : v14.15.1 (/Users/xxx/.nvm/versions/node/v14.15.1/bin/node)
   npm     : 6.14.8
   OS      : macOS Big Sur
   Xcode   : Xcode 12.3 Build version 12C33
```

### PR DESCRIPTION
**Pull request by liamdebeasi**
Issue number: resolves #22940

---------

## What is the current behavior?

Scroll assist does not run when changing keyboards. This means that inputs can be hidden under the keyboard if the new keyboard is larger than the previous keyboard.

## What is the new behavior?

- On Browsers/PWAs scroll assist will re-run when the keyboard geometry changes. We don't have a cross-browser way of detecting keyboard changes yet, so this is the best we have for now.
- On Cordova/Capacitor scroll assist will re-run when the keyboard changes, even if the overall keyboard geometry does not change.

In the example below, we are changing keyboards while an input is focused:
| `main` | branch |
| - | - |
| <video src="https://github.com/ionic-team/ionic-framework/assets/2721089/715e176a-6724-4308-ae3e-15b5bea308ac"></video> | <video src="https://github.com/ionic-team/ionic-framework/assets/2721089/b9ccd482-720a-409b-a089-b3330c1e405c"></video> |

Breakdown per-resize mode:

| Native | None | Ionic | Body |
| - | - | - | - |
| <video src="https://github.com/ionic-team/ionic-framework/assets/2721089/b930ac5f-3398-4887-a8ca-a57708adc66d"></video> | <video src="https://github.com/ionic-team/ionic-framework/assets/2721089/68465854-94d0-4e00-940c-c4674a43b6a3"></video> | <video src="https://github.com/ionic-team/ionic-framework/assets/2721089/561f313a-9caf-4c9e-ab15-9c4383f0e3ee"></video> | <video src="https://github.com/ionic-team/ionic-framework/assets/2721089/300b8894-ad2a-43bc-8e82-ecd68afd407e"></video> |

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Dev build: `7.3.4-dev.11694706860.14b2710d`

### CODE REVIEW

File: core/src/utils/browser/index.ts [hunk 1]
```diff
@@ -20,6 +20,26 @@
  * Note: Code inside of this if-block will
  * not run in an SSR environment.
  */
-export const win: Window | undefined = typeof window !== 'undefined' ? window : undefined;
+
+/**
+ * Even listeners on the window typically expect
```
Comment (amandaejohnston) [inline core/src/utils/browser/index.ts:25]:
```suggestion
 * Event listeners on the window typically expect
```

**Review by amandaejohnston — APPROVED** [review]
