### PR TITLE
fix(angular): add missing menu controller methods

### LINKED ISSUE #20053: bug: angular, isAnimating() not defined on menu controller provider
**Ionic version:**
4.11.5

**Current behavior:**
when i import menu controller into a page component, i saw from the official ionic website listed got a method to detect is the menu animating or not. [Link to Doc](https://ionicframework.com/docs/api/menu-controller)

image

but i couldn't find the method when writing code, IDE prompting method not found during compile and browser also say method not found.

**Expected behavior:**
it should be able to find the method and return the menu is animating or not.

**Steps to reproduce:**
1) just import the menu controller in any module, and write like ```this.menu.isAnimating()```, it will show not found error

**Related code:**

**Ionic info:**

image

image

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)             : 4.11.0 (C:\Users\oks\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.11.5
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.1.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : browser 5.0.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 5 other plugins)

System:

   NodeJS : v10.15.3 (D:\Program\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

### PR DESCRIPTION
**Pull request by thetaPC**
Issue number: resolves #20053 

---------

## What is the current behavior?

There are a few methods that that are missing for the menu in the Angular packages. This leads to users to not being able to use methods like `isAnimating()`. 

## What is the new behavior?

- The missing methods have been added by implementing `MenuControllerI`.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Dev build: 7.5.8-dev.11701461830.1be851fd

### CODE REVIEW

File: packages/angular/common/src/providers/menu-controller.ts [hunk 1]
```diff
@@ -1,6 +1,7 @@
-import type { MenuControllerI } from '@ionic/core/components';
+import type { MenuControllerI, AnimationBuilder, MenuI } from '@ionic/core/components';
+import { Animation } from '@ionic/core/components';
```
Comment (sean-perkins) [inline packages/angular/common/src/providers/menu-controller.ts:2]: Can `Animation` be moved to a type import in the previous import statement?

**Review by sean-perkins — CHANGES_REQUESTED** [review]

File: packages/angular/common/src/providers/menu-controller.ts (hunk 1 above)
Comment (thetaPC) [reply packages/angular/common/src/providers/menu-controller.ts]: Good catch, thanks!

File: packages/angular/common/src/providers/menu-controller.ts [hunk 2]
```diff
@@ -1,6 +1,7 @@
-import type { MenuControllerI } from '@ionic/core/components';
+import type { MenuControllerI, AnimationBuilder, MenuI, Animation } from '@ionic/core/components';
+// import { Animation } from '@ionic/core/components';
```
Comment (sean-perkins) [inline packages/angular/common/src/providers/menu-controller.ts:2]: This needs to be removed.

**Review by sean-perkins — CHANGES_REQUESTED** [review]

File: packages/angular/common/src/providers/menu-controller.ts (hunk 2 above)
Comment (thetaPC) [reply packages/angular/common/src/providers/menu-controller.ts:2]: 🤦‍♀️

**Review by sean-perkins — APPROVED** [review]
Great work!
