### PR TITLE
fix(all): Ionic components that use child Ionic components are now correctly defined

### LINKED ISSUE #23571: bug: custom elements build, ionic components not defining children
# Bug Report

**Ionic version:**

[ ] **4.x**
[ ] **5.x**
[x] **6.x**

**Current behavior:**
Using the `ion-select` Vue component in combination with the option `interface="popover"` doesn't work correctly. If the popover gets triggered, the content is not displayed correctly in v6-beta.0, as you can see from the screenshots below.

v5:

Screenshot 2021-07-02 at 10 43 20

v6:

Screenshot 2021-07-02 at 10 43 51

**Expected behavior:**
Popover of `ion-select` component should be displayed correctly.

**Steps to reproduce:**
Sample code for v5: https://github.com/tho-masn/ionic-issues/tree/v5-ion-select-popover
Sample code for v6: https://github.com/tho-masn/ionic-issues/tree/v6-ion-select-popover

### PR DESCRIPTION
**Pull request by willmartian**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: resolves #23571, #24116, #24129

## What is the new behavior?

- Ionic components will now auto define any dependent components used in their shadow DOM. For example, `ion-select` will now define `ion-select-popover` in the custom elements registry. This allows developers to only worry about importing top level components without worry what they render. 

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: core/src/utils/overlays.ts [hunk 1]
```diff
@@ -43,9 +50,17 @@ export const prepareOverlay = <T extends HTMLIonOverlayElement>(el: T) => {
   }
 };
 
-export const createOverlay = <T extends HTMLIonOverlayElement>(tagName: string, opts: object | undefined): Promise<T> => {
+export const createOverlay = <T extends HTMLIonOverlayElement>(tagName: string, opts: object | undefined, customElement?: any): Promise<T> => {
   /* tslint:disable-next-line */
   if (typeof customElements !== 'undefined') {
+    if (
```
Comment (liamdebeasi) [inline core/src/utils/overlays.ts:56]: Can we stick to a single convention of either accessing `customElements` or `window.customElements`?

Comment (willmartian) [reply core/src/utils/overlays.ts:56]: Yes, good catch. 👍
