### PR TITLE
fix(react): setting active tab properly on mount, closes #21830

### LINKED ISSUE #21830: bug: Tabs navigation broken if landing route redirects to a tab != first tab
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.3.1**

**Current behavior:**
If the default Route points to a tab different from the first one, then click on the first tab doesn't switch to tab1 view.

**Expected behavior:**

**Steps to reproduce:**

`git clone https://github.com/visciang/test2App.git`
`ionic serve`

Click on Tab1. The view still show Tab2

Project created with `ionic start testApp tabs --type=react`

with this addition only https://github.com/visciang/test2App/commit/0eb8a1020a93ecdfab055d2cb070c6c2c69889d2

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.10.2 (/home/gvisciano/.asdf/installs/nodejs/14.3.0/.npm/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.3.1

Capacitor:

   Capacitor CLI   : 2.4.0
   @capacitor/core : 2.4.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.3.0 (/home/gvisciano/.asdf/installs/nodejs/14.3.0/bin/node)
   npm    : 6.14.5
   OS     : Linux 5.4
```

### PR DESCRIPTION
**Pull request by elylucas**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

File: packages/react/src/components/navigation/IonTabBar.tsx [hunk 1]
```diff
@@ -51,15 +51,8 @@ class IonTabBarUnwrapped extends React.PureComponent<InternalProps, IonTabBarSta
...
-    const tabKeys = Object.keys(tabs);
-    const activeTab = tabKeys
-      .find(key => {
-        const href = tabs[key].originalHref;
-        return props.routeInfo!.pathname.startsWith(href);
-      }) || tabKeys[0];
-
     this.state = {
-      activeTab,
+      // activeTab,
```
Comment (liamdebeasi) [inline packages/react/src/components/navigation/IonTabBar.tsx:55]: Do we need to have this here?

Comment (elylucas) [reply packages/react/src/components/navigation/IonTabBar.tsx]: fixed thanks
