### PR TITLE
fix(toast): screen readers announce content

### LINKED ISSUE #25866: bug(a11y): assertive toast not announced
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

The toast message in not announced by screenreaders even with aria-live='assertive'.

Tested with:
- Ionic 6.2.4
- NVDA 2022.2.2 on Chrome and Firefox
- JAWS 2022.2207.25 ILM on Chrome and Firefox

### Expected Behavior

According to [ARIA live regions spec](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions):

> aria-live="assertive" should only be used for time-sensitive/critical notifications that absolutely require the user's immediate attention. Generally, a change to an assertive live region will interrupt any announcement a screen reader is currently making. As such, it can be extremely annoying and disruptive and should only be used sparingly.

So I expect assertive toast message to be announced when toast is shown.

### Steps to Reproduce

- Checkout v.6.2.4
- npm install in ./core
- npm start
- go to http://localhost:3333/src/components/toast/test/a11y using Chrome/Firefox
- launch NVDA/JAWS
- click on 'Present Assertive Toast'
- no announcement

I could provide a demo app using @ionic/angular, but I need to test the toast behaviour with JAWS (with NVDA on Chrome/Firefox is not working).

### Code Reproduction URL

_No response_

### Ionic Info

[WARN] You are not in an Ionic project directory. Project context may be missing.

Ionic:                        
                              
   Ionic CLI : 5.4.16         
                              
Utility:                      
                              
   cordova-res : not installed
   native-run  : not installed
                              
System:                       
                              
   NodeJS : v14.17.1          
   npm    : 6.14.13           
   OS     : Linux 4.4         

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by liamdebeasi**
Issue URL: resolves #25866

---------

Docs PR: https://github.com/ionic-team/ionic-docs/pull/2914

 

 

## What is the current behavior?

NVDA is not announcing toasts on present.

## What is the new behavior?

- Toast has a "status" role and "polite" announcement.
- We also revisited the intended behavior of toasts to better align with the Material Design v2 spec: https://m2.material.io/components/snackbars/web#accessibility

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Dev build: 7.0.3-dev.11681482468.19d7784f

### CODE REVIEW

File: core/src/components/toast/toast.tsx [hunk 1]
```diff
@@ -470,13 +508,42 @@ export class Toast implements ComponentInterface, OverlayInterface {
...
+                animation.
+
+                The "key" attribute is used here to force Stencil to render
+                new nodes and not re-use nodes. Otherwise, NVDA would not
+                detect any changes to the live region.
+
+                The "old" content is hidden using aria-hidden otherwise
+                VoiceOver will announce the toast content twice when presenting.
+              */}
+              {!revealContentToScreenReader && this.header !== undefined && this.renderHeader('oldHeader', 'true')}
```
Comment (sean-perkins) [inline core/src/components/toast/toast.tsx:541]: `this.header` and `this.message` are used a few times, should we deconstruct the variable reference above or is there a reason we need to access it directly in each check?

Comment (liamdebeasi) [reply core/src/components/toast/toast.tsx]: Nope, we can deconstruct these. Fixed in https://github.com/ionic-team/ionic-framework/pull/27198/commits/ab37f25d8bb9997c90b7026c1109795ebcccaf3f
