### PR TITLE
fix(angular): menu button is enabled with Angular Universal builds

### LINKED ISSUE #27524: bug: Split Pane is broken in SSR (after fix)
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v6.x, v7.x

### Current Behavior

When Server Side Rendering is used, the `ion-split-pane` component is broken. The menu pane will not show up along with any menu-button in the page toolbar. Client-side hydration does not make it re-appear.
This is related to issue #24714, which was supposedly 'fixed' in #26854.

Unfortunately this turns half-broken SSR websites (which needed client hydration) into completely broken websites because client hydration does not fix it, and the menu pane will never show up.

### Expected Behavior

Either the ion-split-pane shows up nicely in server-side-rendered pages, or it does not show up but client-side hydration fixes it (old behavior).

### Steps to Reproduce

Taken from my comment on the linked issue:
# 1. Create the project
```bash
ionic start myApp sidemenu --type angular
cd myApp
npm install @angular/animations
ng add @nguniversal/express-engine
npm install @ionic/angular-server
```
(you might need to run `npx ionic start`...)
# 2. Enable Ionic SSR
And updating app.server.module.ts with:
```diff
 import { NgModule } from '@angular/core';
 import { ServerModule } from '@angular/platform-server';
 import { AppModule } from './app.module';
 import { AppComponent } from './app.component';

+ import { IonicServerModule } from '@ionic/angular-server';

 @NgModule({
   imports: [
     AppModule,
     ServerModule,
+    IonicServerModule
   ],
   bootstrap: [AppComponent],
 })
 export class AppServerModule {}
```
# 3. Update server.js
I had to update `server.js` because `node:fs` and `node:path` could not be found.
```diff
 import { APP_BASE_HREF } from '@angular/common';
 import { ngExpressEngine } from '@nguniversal/express-engine';
 import * as express from 'express';
-import { existsSync } from 'node:fs';
+import { existsSync } from 'fs';
-import { join } from 'node:path';
+import { join } from 'path';
 import { AppServerModule } from './src/main.server';
```

# 4. Run
Build & serve the application with:
```bash
npm run build:ssr
npm run serve:ssr
```

### Code Reproduction URL

https://github.com/Tvde1/ion-split-pane-SSR-bug-repro

### Ionic Info

```
Ionic:

   Ionic CLI                     : 5.4.16 (C:\Users\[...]\AppData\Local\npm-cache\_npx\864a9e3c2cd0cf50\node_modules\ionic)
   Ionic Framework               : not installed
   @angular-devkit/build-angular : 16.0.2
   @angular-devkit/schematics    : 16.0.2
   @angular/cli                  : 16.0.2
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI   : 5.0.3
   @capacitor/core : 5.0.3

Utility:

   cordova-res : not installed
   native-run  : 1.7.2

System:

   NodeJS : v20.2.0 (C:\Program Files\nodejs\node.exe)
   npm    : 9.6.6
   OS     : Windows 10
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by sean-perkins**
Issue number: Resolves #27524 #22206

---------

## What is the current behavior?

After destructive hydration from an Angular Universal build, the `ion-menu` is disabled. This results in a few problematic behaviors:
- If used with an `ion-split-pane`, the split pane will not render with the menu.
- If used with an `ion-menu-button`, the menu icon will not render and the menu will not be accessible.

## What is the new behavior?

- Removes automatically disabling the `ion-menu` when in a server environment.
- Prevents setting an `ion-menu` that no longer exists in the DOM, as an active menu. This allows the most recent menu to be enabled when rendered from Angular Universal builds.

Loom recording overviewing the change: https://www.loom.com/share/5a149218adc84cc2af435fc1b1f45124?sid=249028f4-be3d-4d4a-948a-597da83be95a

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Dev-build: `7.1.4-dev.11689625795.1d16532b`

### CODE REVIEW

File: core/src/components/menu/menu.tsx [hunk 1]
```diff
@@ -705,9 +704,18 @@ export class Menu implements ComponentInterface, MenuI {
       this.forceClosing();
     }
 
-    if (!this.disabled) {
-      menuController._setActiveMenu(this);
+    if (document.contains(this.el)) {
```
Comment (liamdebeasi) [inline core/src/components/menu/menu.tsx:707]: Can we use https://github.com/ionic-team/ionic-framework/blob/aa9ea60357c369452bc121c0d663be7dbf3da28e/core/src/utils/browser/index.ts#L25 instead?

Comment (sean-perkins) [reply core/src/components/menu/menu.tsx]: Addressed here: https://github.com/ionic-team/ionic-framework/pull/27814/commits/5437b79fadabffecbc57ffc875ec0269abb0bb7d

**Review by amandaejohnston — APPROVED** [review]
