### PR TITLE
fix(radio): persist checked state when items are updated in radio-group

### LINKED ISSUE #29442: bug: ion-radio does not keep checked-state after updating the underlaying object
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x

### Current Behavior

Initially, the `ion-radio-button` is checked correctly. But after updating the objects that contain the data that is used to display the ion-radion-buttons, the checked-state gets lost, even though the `value` property stays the same. Seems that this bug appears on Angular standalone projects.

Perhaps this error could be related to the following issue: https://github.com/ionic-team/ionic-framework/issues/29414
It could also be that this error can be found in other components, such as `ion-accordion`.

### Expected Behavior

The active ion-radio-button should be highlighted when it's value matches the value of it's containing ion-radio-group - as was the case before standalone components.

### Steps to Reproduce

1. Go to https://stackblitz.com/edit/angular-vquurr-ec7ark?file=src%2Fapp%2Fexample.component.html
2. Click the "Update Data" Button

### Code Reproduction URL

https://stackblitz.com/edit/angular-vquurr-ec7ark?file=src%2Fapp%2Fexample.component.html

### Ionic Info

   Ionic CLI                     : 7.2.0
   Ionic Framework               : @ionic/angular 8.0.1
   @angular-devkit/build-angular : 17.3.6
   @angular-devkit/schematics    : 17.3.6
   @angular/cli                  : 17.3.6
   @ionic/angular-toolkit        : 11.0.1

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by thetaPC**
Issue number: resolves #29442

---------

## What is the current behavior?

The state does not stay consistent when the data used to render the radios are updated.

## What is the new behavior?

- The state updates after the component loads, this allows the value to be set after the radio is rendered.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Dev build: 8.1.1-dev.11714760012.1eab947e

### CODE REVIEW

File: core/src/components/radio/radio.tsx [hunk 1]
```diff
@@ -110,6 +110,18 @@ export class Radio implements ComponentInterface {
    */
   @Event() ionBlur!: EventEmitter<void>;
 
+  componentDidLoad() {
+    /**
+     * The value may be `undefined` if the it
```
Comment (sean-perkins) [inline core/src/components/radio/radio.tsx:115]:
```suggestion
     * The value may be `undefined` if it
```

**Review by sean-perkins — CHANGES_REQUESTED** [review]
Minor docs wording adjustment.

**Review by sean-perkins — APPROVED** [review]
Great work 👍
