### PR TITLE
fix(datetime): time picker format with hourCycle h23

### LINKED ISSUE #24474: bug: `ion-datetime` timepicker does not respect hour cycle format with min provided
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When setting the minimum DateTime to now (`new Date()`), there is no way to select previous minutes even on a different hour.
And the hour wheel doesn't respect the default h23 even when specified.

### Expected Behavior

1. The min value should restrict only up to what is specified. if minimum was set to 19:30, I should be able to select 20:everthing else
2. The hour should stick to the default hour system or the specified one

### Steps to Reproduce

https://user-images.githubusercontent.com/12111716/147143799-39426950-d69e-438c-8b34-f793f4e727c7.mp4

```
  now = moment().add(1, 'h').format();
  minInsterval: number[];
  dateTime:any

ngOnInit() {
    const min = 0,
      max = 55,
      interval = 5;

    const length = (max - min) / interval + 1;
    this.minInsterval = Array.from({ length }, (_, i) => min + i * interval);
  }
```

```
<ion-datetime
        #calendar
        size="cover"
        hourCycle="h23"
        [min]="now"
        [minuteValues]="minInsterval"
        [(ngModel)]="dateTime"
      >
      </ion-datetime>
```

### Code Reproduction URL

_No response_

### Ionic Info

```
Ionic:

   Ionic CLI                     : 6.18.1 (/Users/jonathan/.nvm/versions/node/v16.13.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.1
   @angular-devkit/build-angular : 13.1.2
   @angular-devkit/schematics    : 13.1.2
   @angular/cli                  : 13.1.2
   @ionic/angular-toolkit        : 5.0.3
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by sean-perkins**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

The time picker display ignores the value of hour cycle. The time picker will also restrict all hour selections to the minimum minute range; even though the time is above the min range.

i.e.: When the minimum time is 19:30, you are unable to select any value under 20:30 when the hour is 20.

Issue Number: Resolves #24474

## What is the new behavior?

- Time picker will return the hours back in 24 hour format when hourCycle is h23
- Time picker allows minute selection above the min range, when the hour is above the min hour (if specified)

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

|Before|After|
|---|---|
|<video src="https://user-images.githubusercontent.com/13732623/147148436-637d0bfb-6437-4583-be96-26f1513886b2.mp4"></video>| <video src="https://user-images.githubusercontent.com/13732623/147146337-f0d23717-ec29-41ad-9cf8-278236c85a0d.mp4"></video>|

### CODE REVIEW

File: core/src/components/datetime/utils/data.ts [hunk 1]
```diff
@@ -166,17 +167,24 @@ export const generateTime = (
...
         isAMAllowed = minParts.hour < 13;
       }
       if (minParts.minute !== undefined) {
-        processedMinutes = processedMinutes.filter(minute => minute >= minParts.minute!);
+        processedMinutes = processedMinutes.filter(minute => {
+          if (minParts.hour !== undefined && refParts.hour !== undefined) {
+            if (refParts.hour > minParts.hour) {
+              return true;
+            }
+          }
```
Comment (amandaesmith3) [inline core/src/components/datetime/utils/data.ts:180]: Could we pull these conditions out into a separate variable outside the loop? Would improve readability and performance.

**Review by amandaesmith3 — CHANGES_REQUESTED** [review]
This looks great! Just one minor thing and then it's a ✅ from me.

File: core/src/components/datetime/utils/data.ts (hunk 1 above)
Comment (sean-perkins) [reply core/src/components/datetime/utils/data.ts:180]: Great call 👍

**Review by amandaesmith3 — APPROVED** [review]

**Review by liamdebeasi — APPROVED** [review]
