### PR TITLE
fix(radio): radio with modern syntax is keyboard navigable

### LINKED ISSUE #27268: bug: Radio group tab navigation is incorrect for modern form control syntax
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

In v7 the tab navigation for `ion-radio-group` is incorrect with the modern form syntax.

Pressing `Tab` will focus the next available `ion-radio` in the group. Once reaching the last radio, it will advance to focus the next available radio in the nearest `ion-radio-group`.

|Legacy|Modern|
|---|---|
|<video src="https://user-images.githubusercontent.com/13732623/234109075-d688d7ab-dfc3-4d7d-bc03-d89ff89ca35a.mp4"></video>|<video src="https://user-images.githubusercontent.com/13732623/234109274-9e2bf07f-5997-4407-bc3a-815e5e64a180.mp4"></video>

### Expected Behavior

Pressing `Tab` should focus the next available option in the nearest `ion-radio-group`. It should not advance to the next `ion-radio` in the current group. The `up/down` arrow keys should be responsible for that behavior.

### Steps to Reproduce

1. Render multiple radio groups with the modern form syntax
2. Press `Tab` (repeatedly)
3. Observe: The next `ion-radio` is focused in the group
4. Observe: The focus will change between the radio groups after reaching the last radio in the group.

---

If using the reproduction, run the app and you can click the "Legacy Syntax" or "Modern Syntax" item to experiment with the different syntax and `Tab` key behavior.

### Code Reproduction URL

https://github.com/sean-perkins/ionic-radio-group-tabs-bug

### Ionic Info

N/A

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by thetaPC**
Issue number: resolves #27268 

---------

## What is the current behavior?

When tabbing on a radio group (modern syntax), it focuses on the next radio option inside the radio group. It replicates the behavior of the up/down keys.

## What is the new behavior?

- When tabbing on a radio group (modern syntax), it focuses on the next radio option of the next radio group.

A spike ticket has been created to further investigate web accessibility and browser compatibility.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

N/A

### CODE REVIEW

File: core/src/components/radio/radio.tsx [hunk 1]
```diff
@@ -24,7 +24,9 @@ import { createColorClasses, hostContext } from '../../utils/theme';
     ios: 'radio.ios.scss',
     md: 'radio.md.scss',
   },
-  shadow: true,
+  shadow: {
+    delegatesFocus: true,
```
Comment (liamdebeasi) [inline core/src/components/radio/radio.tsx:28]: Threading:

This behavior does not work on Safari. Tabbing while focused on the first radio group moves focus to the `body`.


Also pressing the "Down" arrow selects the same radio.

Comment (liamdebeasi) [reply core/src/components/radio/radio.tsx:28]: Also, does tabbing between radio groups work in Safari on `main` with the legacy syntax? If not, then I think a separate ticket to fix that would be fine since we aren't regressing behavior.

Comment (thetaPC) [reply core/src/components/radio/radio.tsx:28]: It does work. However, `<ion-radio>.focus()` [still wouldn't work](https://github.com/ionic-team/ionic-framework/issues/27438). `delegatesFocus` was helping to fix that.
-
Tabbing on radio groups work on `main`. But it stops working if `delegatesFocus` is introduced.

Comment (liamdebeasi) [reply core/src/components/radio/radio.tsx:28]: The PR description links to https://github.com/ionic-team/ionic-framework/issues/27268, but it sounds like we are also trying to fix https://github.com/ionic-team/ionic-framework/issues/27438. I think we are going to have the most luck with this PR if we focus on fixing one bug at a time.

Updating the internal `setFocus` method to focus the native `input` element should fix #27268 since the radio group calls `setFocus`. It sounds like the other issue is something that is specific to Firefox and may require additional investigation.

File: core/src/components/radio/radio.tsx [hunk 2]
```diff
@@ -135,7 +135,7 @@ export class Radio implements ComponentInterface {
     ev.stopPropagation();
     ev.preventDefault();
 
-    this.el.focus();
+    this.nativeInput.focus();
```
Comment (liamdebeasi) [inline core/src/components/radio/radio.tsx:138]: It looks like this causes some issues with the legacy syntax just in Safari. Doing a Shift+Tab to get back to the previous radio group requires pressing Shift+Tab twice.
```suggestion
    const element = this.legacyFormController.hasLegacyControl() ? this.el : this.nativeInput;
    element.focus();
```

Let's keep focusing `this.el` only when in the legacy syntax.

**Review by liamdebeasi — APPROVED** [review]
Good to go once my other comment has been addressed.

Can you make the commit title more descriptive too? Instead of "tab to the next radio group" maybe we say "fix(radio): radio with modern syntax is keyboard navigable"?

Great job!
