### PR TITLE
fix(react): adding a dynamic class to an ion-page no longer hides the…

### LINKED ISSUE #22631: bug: ion-page turning invisible when changing its css class to any value
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.5.1**

**Current behavior:**
When changing the css class of ion-page to any value, ionic adds `ion-page-invisible` which renders the page invisible.  

**Expected behavior:**
`ion-page-invisible` should not be added to list of style classes when changing a page's classes.

**Steps to reproduce:**

1. Set up a page inside `IonReactRouter`
2. Assign any class value to an `ion-page`'s style/classes attribute and display the page
3. Change the class attribute dynamically, i.e via button press 

**Related code:**

https://github.com/larsblumberg/ionic-invisible-page

```
const App: React.FC = () => (
  <IonApp>
    <IonReactRouter>
      <IonRouterOutlet>
        <Route path="/" component={Page} />
      </IonRouterOutlet>
    </IonReactRouter>
  </IonApp>
);

const Page: React.FC = () => {
  const [styleClass, setStyleClass] = useState('initial-class')
  return (
    <IonPage className={styleClass}>
      <IonContent>
        <IonButton onClick={() => setStyleClass('other-class')}>Add Class</IonButton>
      </IonContent>
    </IonPage>
  );
};
```

**Other information:**

Bug doesn't manifest if page is used outside (without) `IonReactRouter`.

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.12.1 (/Users/lars/.config/yarn/global/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.5.1

Capacitor:

   Capacitor CLI   : 2.4.4
   @capacitor/core : 2.4.4

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v15.2.1 (/usr/local/Cellar/node/15.2.1/bin/node)
   npm    : 7.0.10
   OS     : macOS Catalina
```

### PR DESCRIPTION
**Pull request by elylucas**
… page, resolves #22631

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: resolves #22631

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

File: packages/react/src/routing/PageManager.tsx [hunk 1]
```diff
@@ -23,6 +23,9 @@ export class PageManager extends React.PureComponent<PageManagerProps> {
 
   componentDidMount() {
     if (this.ionPageElementRef.current) {
+      if(this.context.isInOutlet()) {
```
Comment (liamdebeasi) [inline packages/react/src/routing/PageManager.tsx:26]:
```suggestion
      if (this.context.isInOutlet()) {
```

**Review by liamdebeasi — APPROVED** [review]
