### PR TITLE
fix(overlay): do not hide overlay if toast is presented

### LINKED ISSUE #29139: bug: Overlays now have aria-hidden=true when displaying a Toast
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

In issue https://github.com/ionic-team/ionic-framework/issues/23472, the behaviour of overlays was modified to add `aria-hidden=true` to existing overlays when displaying a new overlay. IMO this makes sense for modals and popovers, but this shouldn't be done when displaying a Toast. Toasts are overlays that don't block the interaction with the other elements in the DOM, so the rest of overlays should remain active and visible.

### Expected Behavior

Displaying a Toast should not add aria-hidden=true to other overlays.

### Steps to Reproduce

1. In an Ionic app, display any modal using ModalController.create.
2. While the modal is displayed, show a toast with a long duration using ToastController.create.
3. Inspect the DOM and search for the ion-modal. Check that it has aria-hidden="true" while the Toast is displayed.

### Code Reproduction URL

https://github.com/dpalou/overlays-toast-bug

### Ionic Info

Ionic:

   Ionic CLI                     : 7.2.0 (/Users/dpalou/.nvm/versions/node/v18.18.2/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.7.4
   @angular-devkit/build-angular : 17.2.3
   @angular-devkit/schematics    : 17.2.3
   @angular/cli                  : 17.2.3
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.7.2
   @capacitor/android : not installed
   @capacitor/core    : 5.7.2
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 2.0.1

System:

   NodeJS : v18.18.2 (/Users/dpalou/.nvm/versions/node/v18.18.2/bin/node)
   npm    : 9.8.1
   OS     : macOS Unknown

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by liamdebeasi**
Issue number: resolves #29139 

---------

## What is the current behavior?

When implementing https://github.com/ionic-team/ionic-framework/pull/28997 we did not consider the case where a Toast could be presented. When presenting a Toast after presenting a Modal the linked change causes the Modal to be hidden from screen readers.

## What is the new behavior?

- If the top-most overlay is a Toast then the closest non-Toast overlay is also not hidden from screen readers. 

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Dev build: `7.7.5-dev.11710260658.1fc29a6c`

### CODE REVIEW

File: core/src/utils/overlays.ts [hunk 1]
```diff
@@ -966,3 +951,69 @@ export const createTriggerController = () => {
...
+  if (doc === undefined) return;
+
+  const overlays = getPresentedOverlays(doc);
+
+  for (let i = overlays.length - 1; i >= 0; i--) {
+    const presentedOverlay = overlays[i];
+    const nextPresentedOverlay = overlays[i + 1] ?? newTopMostOverlay;
+
+    // If next overlay has aria-hidden then all remaining overlays will have it too.
+    if (nextPresentedOverlay.hasAttribute('aria-hidden')) {
```
Comment (liamdebeasi) [inline core/src/utils/overlays.ts:975]: This may cause issues if the developer decides to present a new overlay with `aria-hidden`. However, I don't know how realistic that scenario is because then screen readers would never be able to focus the new overlay even without this change.

Comment (amandaejohnston) [inline core/src/utils/overlays.ts:975]: This and the `else` block both do the same thing, so the two conditions can be merged into a single `||` statement.

File: core/src/utils/overlays.ts [hunk 2]
```diff
@@ -966,3 +951,69 @@ export const createTriggerController = () => {
...
+
+/**
+ * When dismissing an overlay we need to reveal the new top-most overlay to screen readers.
+ * If the top-most overlay is a Toast we potentially need to reveal more overlays since
+ * focus is never automatically moved to the Toast.
+ */
+const revealOverlaysToScreenReaders = () => {
+  if (doc === undefined) return;
+
+  // If there are other overlays presented, unhide the new topmost one from screen readers.
```
Comment (amandaejohnston) [inline core/src/utils/overlays.ts:995]:
```suggestion
```
This comment no longer has anything to do with the code it's following, and is made redundant by the function's top-level comments.

File: core/src/utils/overlays.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (liamdebeasi) [reply core/src/utils/overlays.ts]: Here's an example:

```
(bottom-most overlay)
modal one
toast one
(top-most overlay)
```

When `toast one` is presented, `modal one` does **not** have `aria-hidden="true"`. If we then present `modal two` then `modal-one` should be hidden from screen readers. However, if we only checked if the next overlay was not a Toast then this wouldn't happen.

[the remark this answers is not in the document]
Comment (amandaejohnston) [reply core/src/utils/overlays.ts]: Ah, got it! Thank you, that makes sense 👍

**Review by amandaejohnston — APPROVED** [review]

**Review by sean-perkins — APPROVED** [review]
