### PR TITLE
fix(react): nav will remove components from the DOM

### LINKED ISSUE #25753: bug: ion-nav does not remove component in DOM or update state correctly
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When using the `IonNav` and `IonNavLink` components in react for routing, going `'forward'` creates a new element in the DOM, but going `'backward'` does not remove that element. This results in multiple duplicate elements being created when navigating backwards then forwards again (with the current screen being shown in a higher `z-index`).

As a side effect, it seems than whenever react state is updated inside the `IonNav` component, a new component is created entirely, rather than updating the state correctly.

### Expected Behavior

Would expect `IonNav` to work correctly in navigating forwards and backwards through `IonNavLink`s without duplicating elements in the DOM, and correctly updating react state within the components.

### Steps to Reproduce

1. Clone: https://github.com/daniel-menezes/ion-nav
2. `npm install`
3. `npm run start`
4. Navigate between pages using the given buttons and see the dom renders duplicate components

 e.g.

```html
<ion-nav delegate="[object Object]">
  <div class="ion-page ion-page-hidden" style="z-index: 100;" aria-hidden="true">...</div>
  <div class="ion-page can-go-back" style="z-index: 100; display: none;">...</div>
  <div class="ion-page can-go-back" style="z-index: 100; display: none;">...</div>
  <div class="ion-page can-go-back" style="z-index: 100; display: none;">...</div>
  <div class="ion-page can-go-back" style="z-index: 100; display: none;">...</div>
  <div class="ion-page can-go-back" style="z-index: 100; display: none;">...</div>
  ...
  <div class="ion-page can-go-back" style="z-index: 101; display: none;">...</div>
</ion-nav>
```

I've used a `NavComponent` as taken from https://github.com/ionic-team/ionic-framework/blob/b2a27e0b623a603b536dc23ab409662219323acb/packages/react/test-app/src/pages/navigation/NavComponent.tsx

### Code Reproduction URL

https://github.com/daniel-menezes/ion-nav

### Ionic Info

Ionic:

   Ionic CLI       : 6.20.1 
   Ionic Framework : @ionic/react 6.2.2

Capacitor:

   Capacitor CLI      : 4.0.1
   @capacitor/android : not installed
   @capacitor/core    : 4.0.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.6.0

System:

   NodeJS : v16.13.0 
   npm    : 8.1.0
   OS     : macOS Monterey

### Additional Information

The first video shows the base example of navigating forwards and backwards with `IonNav` and the DOM creating duplicate components.

https://user-images.githubusercontent.com/61494082/184286345-45d83327-366a-4c85-a34d-9d001ea861f9.mov

The second video shows an example of updating a simple react state counter. The DOM creates a new node with the component in the new state and overlays it underneath the the component with the old state (which can be seen by the `z-index`.

https://user-images.githubusercontent.com/61494082/184286371-d4e40661-6469-4af4-af12-71d7760d4856.mov

### PR DESCRIPTION
**Pull request by sean-perkins**
Issue #: resolves #25753

----------

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
  - Some docs updates need to be made in the `ionic-docs` repo, in a separate PR. See the [contributing guide](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#modifying-documentation) for details.
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

When `IonNav` performs a pop operation (navigating to root, back, etc.) the views are not removed from the DOM. 

## What is the new behavior?

- `IonNav` removes pages from the DOM when they are popped (navigate back, navigate to root, etc.)
- Memoized constructing React delegate (was reconstructing on each render)

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by amandaejohnston — APPROVED** [review]

File: packages/react/src/framework-delegate.tsx [hunk 1]
```diff
@@ -22,17 +22,19 @@ export const ReactDelegate = (
...
 
     return Promise.resolve(div);
   };
 
-  const removeViewFromDom = (_container: any, component: ReactComponent): Promise<void> => {
+  const removeViewFromDom = (_container: any, component: HTMLElement): Promise<void> => {
     const hostComponent = refMap.get(component);
     hostComponent && removeView(hostComponent);
 
+    component.remove();
```
Comment (liamdebeasi) [inline packages/react/src/framework-delegate.tsx:36]: Are there any considerations we need to make with conditionally rendering pages similar to https://github.com/ionic-team/ionic-framework/pull/25663?

**Review by liamdebeasi — APPROVED** [review]

**Review by liamdebeasi — APPROVED** [review]
My question in https://github.com/ionic-team/ionic-framework/pull/25763/files#r952650655 still stands, but otherwise this approach looks great. Nice work!

File: packages/react/src/framework-delegate.tsx (hunk 1 above)
Comment (sean-perkins) [reply packages/react/src/framework-delegate.tsx:38]: I do not believe the same considerations apply for `IonNav`. With `IonModal` the React node is relocated in the DOM and this causes potential issues when the surrounding React nodes are added or removed (causing React to incorrect remove the modal reference - which is why we render the `template` buffer elements). With `IonNav` the React node is stable and the components are added/removed as children of the `IonNav`.

**Review by liamdebeasi — APPROVED** [review]
