### PR TITLE
fix(angular): add ionNavWillChange and ionNavDidChange types for nav

### LINKED ISSUE #29114: bug: Properties ionNavWillChange and ionNavDidChange do not exist on IonNav
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When upgrading to latest Ionic (v7.7.3) the build fails with error:
```
 error TS2339: Property 'ionNavDidChange' does not exist on type 'IonNav'.

44     this.ionNav.ionNavDidChange.subscribe(async () => {
                   ~~~~~~~~~~~~~~~
```

### Expected Behavior

This was not added to the breaking changes, and is still referenced in the documentation.
so the code should still work

### Steps to Reproduce

1. create a property of type `IonNav`
2. try to access ionNavDidChange
3. (IDE will probably error here)
4. run build

### Code Reproduction URL

https://stackblitz.com/edit/ionic-ion-nav-issue-reproduction?file=src%2Fmain.ts

### Ionic Info

Ionic:

   Ionic CLI : 5.4.16

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v21.1.0
   npm    : 10.2.5
   OS     : macOS Unknown

### Additional Information

Bug was already mentioned in https://github.com/ionic-team/ionic-framework/issues/28863 but closed without checking it properly.

### PR DESCRIPTION
**Pull request by sean-perkins**
Issue number: resolves #29114

---------

## What is the current behavior?

The event types for `ion-nav` were not correctly applied to the angular component wrapper.

## What is the new behavior?

- `ionNavWillChange` and `ionNavDidChange` event types are added to `ion-nav` component wrapper in Angular.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Dev-build: `7.7.5-dev.11709823131.1d3df428`

Testing:
- Open reproduction on original issue
- Observe: Type errors for missing event properties 
- Install dev-build
- (May need to reload)
- Observe: Type errors are resolved

### CODE REVIEW

File: packages/angular/common/src/directives/navigation/nav.ts [hunk 1]
```diff
@@ -23,7 +31,16 @@ const NAV_METHODS = [
 ];
 
 // eslint-disable-next-line @typescript-eslint/no-empty-interface
```
Comment (thetaPC) [inline packages/angular/common/src/directives/navigation/nav.ts:33]: I think we can remove this `eslint` disable rule.

**Review by thetaPC — CHANGES_REQUESTED** [review]

**Review by thetaPC — APPROVED** [review]
LGTM
