### PR TITLE
fix(core): swipe to go back gesture has priority over other horizontal swipe gestures

### LINKED ISSUE #28303: bug: ion-item-sliding inconsistently clobbers page swipe back gesture
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

This is inconsistent to reproduce (~50% of the time): Any ion-item-sliding will capture a swipe back gesture so that the user accidentally swipes the item instead of the page.

### Expected Behavior

Swipe back gesture should always have priority over ion-item-sliding

### Steps to Reproduce

- In repro below, tap to go to inner page
- Try to swipe back. Observe ion-item-sliding sometimes overrides swipe page back gesture

### Code Reproduction URL

https://github.com/aeharding/ionic-swipe-back-gesture-bug

### Ionic Info

```
[WARN] You are not in an Ionic project directory. Project context may be missing.

Ionic:

   Ionic CLI : 7.1.1

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v18.15.0
   npm    : 9.5.0
   OS     : macOS Unknown
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by aeharding**
Issue number: resolves #28303

---------

## What is the current behavior?

- Swipe back gesture is inconsistently clobbered by ion-item-sliding's gesture.

## What is the new behavior?

- Swipe back gesture now has a higher priority than ion-item-sliding
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

This patch has been in use in [Voyager](https://github.com/aeharding/voyager) for the past couple months to great success!

### CODE REVIEW

File: core/src/utils/gesture/swipe-back.ts [hunk 1]
```diff
@@ -79,7 +79,7 @@ export const createSwipeBackGesture = (
   return createGesture({
     el,
     gestureName: 'goback-swipe',
-    gesturePriority: 40,
+    gesturePriority: 101,
```
Comment (liamdebeasi) [inline core/src/utils/gesture/swipe-back.ts:82]:
```suggestion
    /**
     * Swipe to go back should have priority over other horizontal swipe
     * gestures. These gestures have a priority of 100 which is why 101 was chosen here.
     */
    gesturePriority: 101,
```

We should probably update these values to use a const/enum, but this should be fine for now.

**Review by liamdebeasi — COMMENTED** [review]
Changes look good. Was able to verify this locally:
| main | branch |
| - | - |
| <video src="https://github.com/ionic-team/ionic-framework/assets/2721089/99cd3d69-0fb3-43ac-a9a7-25b379246202"></video> | <video src="https://github.com/ionic-team/ionic-framework/assets/2721089/1b2ce9f0-6c5b-4fef-9057-f5b5d4ad82b8"></video> |

**Review by liamdebeasi — APPROVED** [review]
Thank you!
