### PR TITLE
fix(datetime): support typing time values in a 24-hour format

### LINKED ISSUE #28877: bug: datetime, typing 20:00 selects 02:00
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

In the ion-datetime component, when typing 2000 in the keyboard the resulted time value is 0200 

Examples: https://forum.ionicframework.com/t/ion-datetime-disable-opening-keyboard/224558/6?u=dennisskylegs

### Expected Behavior

Expect when typing 2000 the result is 20:00.

### Steps to Reproduce

1. Go to ion-datetime component (24h format): https://ionicframework.com/docs/api/datetime
2. Select time
3. Select time to highlight
4. type 2000

### Code Reproduction URL

_No response_

### Ionic Info

Ionic:

   Ionic CLI                     : 7.2.0 (/Users/dennis/.nvm/versions/node/v21.5.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.6.5
   @angular-devkit/build-angular : 15.2.10
   @angular-devkit/schematics    : 15.2.10
   @angular/cli                  : 15.2.10
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 4.8.1
   @capacitor/android : 4.8.1
   @capacitor/core    : 4.8.1
   @capacitor/ios     : 4.8.1

Utility:

   cordova-res                          : 0.15.4
   native-run (update available: 2.0.0) : 1.7.4

System:

   NodeJS : v21.5.0 (/Users/dennis/.nvm/versions/node/v21.5.0/bin/node)
   npm    : 10.2.4
   OS     : macOS Unknown

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by vunizhona**
- Adjusted the `selectMultiColumn` logic to handle keyboard values like 20 and 22 dynamically.
- Introduced checks for the maximum column value to enable flexible input behavior.
- Added e2e tests to verify correct value selection for both 12-hour and 24-hour formats.

Issue number: resolves #28877

---------

## What is the current behavior?

In the ion-datetime component, when typing 2000 in the keyboard the resulted time value is 02:00 (in 24-hour format)

Examples: https://forum.ionicframework.com/t/ion-datetime-disable-opening-keyboard/224558/6?u=dennisskylegs

## What is the new behavior?
In the ion-datetime component, when typing 2000 in the keyboard the resulted time value is 20:00 (in 24-hour format)

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by vunizhona** [comment]
> We need this update so our project can work properly. Are there any timeframes when this can be looked at? @brandyscarney

There is one slightly annoying case with inputting hours within the 1-9 range. For 3-9, these hour values can be put by simply inputting the single-digit value. but for the 1 and 2, it’s impossible since the current logic puts it into the 1st place. The problem could be solved by allowing inputting single-digit values in double-digit representation with 0 in the first place (many pickers allow that logic)

We should consider how to resolve that case as well.

File: core/src/components/picker/picker.tsx [hunk 1]
```diff
@@ -410,15 +410,61 @@ export class Picker implements ComponentInterface {
...
       colEl.setValue(option.value);
     }
+
+    return !!option;
+  };
+
+  /**
+   * Attempts to intelligently search the first and second
+   * column as if they're number columns for the provided numbers
+   * where the first two numbers inpu are the first column
```
Comment (thetaPC) [inline core/src/components/picker/picker.tsx:434]: Do you mean to say?

```suggestion
   * where the first two numbers are the first column
```

File: core/src/components/picker/picker.tsx [hunk 2]
```diff
@@ -410,15 +410,61 @@ export class Picker implements ComponentInterface {
...
+      if (!singleDigitFound) {
+        inputArray.shift();
+        singleDigitHour = inputArray[0];
+        singleDigitFound = this.searchColumn(firstColumn, singleDigitHour);
+      }
+
+      if (singleDigitFound && inputArray.length > 1) {
+        const remainingDigits = inputArray.slice(1, 3).join('');
+        this.searchColumn(secondColumn, remainingDigits);
+      }
```
Comment (thetaPC) [inline core/src/components/picker/picker.tsx:466]: It would be great to have comments explaining what the if statements are doing to speed up the debugging/review process for devs.

File: core/src/components/picker/test/keyboard-entry/picker.e2e.ts [hunk 3]
```diff
@@ -163,6 +163,100 @@ configs({ modes: ['ios'], directions: ['ltr'] }).forEach(({ title, config }) =>
       await expect(ionChange).toHaveReceivedEventDetail({ value: 12 });
       await expect(column).toHaveJSProperty('value', 12);
     });
+
+    test('should allow typing 22 in a column where the max value is 23 and not just set it to 2', async ({ page }) => {
+      await page.setContent(
```
Comment (thetaPC) [inline core/src/components/picker/test/keyboard-entry/picker.e2e.ts:168]: Since these tests are related to an issue, we add an annotation to make sure we don't forgot why we added them in in the first place.

```suggestion
      testInfo.annotations.push({
         type: 'issue',
         description: 'https://github.com/ionic-team/ionic-framework/issues/28877',
      });
      await page.setContent(
```

File: core/src/components/picker/test/keyboard-entry/picker.e2e.ts [hunk 4]
```diff
@@ -163,6 +163,100 @@ configs({ modes: ['ios'], directions: ['ltr'] }).forEach(({ title, config }) =>
...
+      await page.keyboard.press('Digit2');
+      await page.keyboard.press('Digit2');
+
+      // Ensure the column value is updated to 22
+      await expect(ionChange).toHaveReceivedEventDetail({ value: 22 });
+      await expect(column).toHaveJSProperty('value', 22);
+    });
+
+    test('should set value to 2 and not wait for another digit when max value is 12', async ({ page }) => {
+      await page.setContent(
```
Comment (thetaPC) [inline core/src/components/picker/test/keyboard-entry/picker.e2e.ts:212]: Since these tests are related to an issue, we add an annotation to make sure we don't forgot why we added them in in the first place.

```suggestion
      testInfo.annotations.push({
         type: 'issue',
         description: 'https://github.com/ionic-team/ionic-framework/issues/28877',
      });
      await page.setContent(
```

**Review by thetaPC — CHANGES_REQUESTED** [review]

File: core/src/components/picker/test/keyboard-entry/picker.e2e.ts (hunk 3 above)
Comment (ShaneK) [reply core/src/components/picker/test/keyboard-entry/picker.e2e.ts:172]: I didn't even know about this, rad!

File: core/src/components/picker/picker.tsx (hunk 2 above)
Comment (thetaPC) [reply core/src/components/picker/picker.tsx]: Thank you! Datetime is already complex so having more comments should help us in the future.

**Review by thetaPC — APPROVED** [review]
LGTM

**Review by brandyscarney — APPROVED** [review]
Looks great, thank you both for all of your work on this! 🚀

**Comment by ShaneK** [comment]
Congrats on your first PR to Ionic Framework, @vunizhona! This will be merged to main as soon as it's done going through its final checks, then it'll be out with our next patch, which should happen very soon!

Thank you for your work on resolving this issue 💪
