### PR TITLE
fix(modal): swipe to close modal is no longer swipeable on footer

### LINKED ISSUE #23398: bug: swipe to close modal should not be swipeable on the footer
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

If i create a Modal, that uses swipeToClose iOS Mode and has a Footer, i'm able to swipe down on that Footer to close the Modal.

**Expected behavior:**

It should only be possible when swiping the Header?

**Steps to reproduce:**

Open Stachblitz, use iOS version of the Browser

**Related code:**

Stackblitz: https://ionic-angular-v5-jraezm.stackblitz.io

### PR DESCRIPTION
**Pull request by EinfachHans**
closes #23398

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [X] Build (`npm run build`) was run locally and any changes were pushed
- [X] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

An iOS Card Style Modal is currently able to swipe down on the Footer.

Issue Number: #23398 

## What is the new behavior?

- According to @liamdebeasi 's comments in my issue i edited the code to make the gesture not be start-able on the footer as well

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

File: core/src/components/modal/gestures/swipe-to-close.ts [hunk 1]
```diff
@@ -24,11 +24,11 @@ export const createSwipeToCloseGesture = (
...
     }
 
-    const content = target.closest('ion-content');
-    if (content === null) {
+    const contentOrFooter = target.closest('ion-content, ion-footer');
+    if (contentOrFooter === null) {
       return true;
     }
-    // Target is in the content so we don't start the gesture.
+    // Target is in the content or the footer so we don't start the gesture.
```
Comment (liamdebeasi) [inline core/src/components/modal/gestures/swipe-to-close.ts:31]:
```suggestion
    // Target is in the content or the footer so do not start the gesture.
```

GitHub Actions had an outage yesterday, so I need to add a new commit that will get the actions to fire again ;)

**Review by liamdebeasi — APPROVED** [review]
Great job! I tested and this is working as expected now.

**Comment by liamdebeasi** [comment]
Merged. Thank you for the PR!
