### PR TITLE
fix(select): click handlers on slotted content fire

### LINKED ISSUE #28818: bug: v7 - React - onClick doesn't work in ionButton inside ionSelect
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

The new functionality insert ionButton inside ionSelect work noramly to visualize but when is insert a function like the onClick dosen't work, the event isn't fired, have othen events that work normaly like onTouch(Start or End).

### Expected Behavior

Just when insert the onClick and click the event be fire.

### Steps to Reproduce

```
<IonSelect
        label='Level 1'
        placeholder="Select Level 1"
        labelPlacement="floating"
        fill="solid"
        value={'test'}
        onIonChange={e=>{}}
>
       <IonSelectOption value="test">Opt</IonSelectOption>
       <IonButton fill="clear" slot="end" onClick={e=>{alert('fire')}}>
          <IonIcon slot="icon-only" color='dark' icon={addCircle}></IonIcon>
       </IonButton>
</IonSelect>
```

### Code Reproduction URL

_No response_

### Ionic Info

[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package.json'

       Require stack:
       - C:\Users\Arcano\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\Arcano\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\Arcano\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\Arcano\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic

Ionic:

   Ionic CLI       : 7.1.1 (C:\Users\Arcano\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 7.6.4

Capacitor:

   Capacitor CLI      : 5.4.1
   @capacitor/android : 5.4.1
   @capacitor/core    : 5.4.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.3

System:

   NodeJS : v18.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 9.5.1
   OS     : Windows 10

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by liamdebeasi**
Issue number: resolves #28818

---------

## What is the current behavior?

Select has logic in place to prevent the overlay from opening when clicking the slotted content. As part of this, we need to deal with the `<label>` element dispatching another click that then bubbles up and causes the overlay to open when clicking the slotted content. We currently deal with this by calling `preventDefault` which prevents this extra event from being dispatched only when clicking the slotted content.

We also call `stopPropagation`. This code is not necessary, and in most cases should not have any adverse effects on developer applications. However, this does impact React applications due to how React handles events. When a developer places `onClick` on a slotted element, a native "click" listener is not immediately applied to that element. Instead, React adds a native "click" listener to the root element of an application. When that listener's callback fires, React will dispatch a synthetic click event on the slotted element. Since we are calling `stopPropagation`, the click event never bubbles up to this root node's listener. As a result, the synthetic event is never dispatched on the slotted element, and the developed `onClick` callback never fires.

## What is the new behavior?

- Select no longer prevents events from bubbling. The existing `event.preventDefault` is sufficient to prevent the label from dispatching another click (thereby causing the select overlay to open) when clicking the slotted content.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Dev build: `7.6.5-dev.11705430252.1023daf3`

### CODE REVIEW

File: core/src/components/select/select.tsx [hunk 1]
```diff
@@ -772,12 +772,26 @@ export class Select implements ComponentInterface {
       this.open(ev);
     } else {
       /**
-       * Prevent clicks to the start/end slots from opening the select.
-       * We ensure the target isn't this element in case the select is slotted
-       * in, for example, an item. This would prevent the select from ever
-       * being opened since the element itself has slot="start"/"end".
```
Comment (amandaejohnston) [inline core/src/components/select/select.tsx:778]: Can we ensure this context is preserved somewhere, whether in this specific comment or elsewhere (such as near the `target === this.el` check above)?

File: core/src/components/select/test/select.spec.tsx [hunk 2]
```diff
@@ -69,3 +69,31 @@ describe('ion-select', () => {
     expect(slotEl).toBe(null);
   });
 });
+
+describe('select: slot interactivity', () => {
```
Comment (amandaejohnston) [inline core/src/components/select/test/select.spec.tsx:73]: Should we have a test in the React app too, since the problem was specific to that?

Comment (liamdebeasi) [reply core/src/components/select/test/select.spec.tsx:73]: The bug most easily reproduces in React, but it's not specific to the React environment which is why I decided to make this a test in core instead of a test in React.

File: core/src/components/select/select.tsx (hunk 1 above)
Comment (liamdebeasi) [reply core/src/components/select/select.tsx]: re-added in https://github.com/ionic-team/ionic-framework/pull/28839/commits/03bd74dd9909f89b1fa8e76e7fcc4743bf1ffa2a

**Review by amandaejohnston — APPROVED** [review]
