### PR TITLE
fix(segment-button): update checked state on render

### LINKED ISSUE #26830: bug: ion-segment does not reflect the initial value of [value] when rendering component
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [ ] v6.x
- [X] v7.x
- [ ] Nightly

### Current Behavior

ion-segment does not show the current state of [value] as 'active' when the component is initialized:

image

### Expected Behavior

Component should visually reflect that the value has been set and one of the segments is active:

image

### Steps to Reproduce

```
  <ion-segment #segment [value]="segment" [swipeGesture]=false
    (ionChange)="updateSegment(segment.value)">
    <ion-segment-button *ngFor="let seg of segments"
      [disabled]='seg === "rulings"'
      [value]="seg">
      <ion-label>{{ seg | titlecase }}</ion-label>
    </ion-segment-button>
  </ion-segment>
```

```
@Component({
  selector: 'app-tab1',
  templateUrl: 'tab1.page.html',
  styleUrls: ['tab1.page.scss']
})
export class Tab1Page {

  public segments = ['general', 'detail', 'versions', 'rulings', 'other'];
  public segment = 'detail';

  updateSegment(value: string | undefined){
    this.segment = value as string;
  }

}

```

Load the page, segments will not reflect that the current value is 'details'.

### Code Reproduction URL

_No response_

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.3 (/Users/lincoln/.nvm/versions/node/v16.14.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.0.0-dev.11676644846.156e8507
   @angular-devkit/build-angular : 15.1.6
   @angular-devkit/schematics    : 15.1.6
   @angular/cli                  : 15.1.6
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.6.3
   @capacitor/android : not installed
   @capacitor/core    : 4.6.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.1

System:

   NodeJS : v16.14.0 (/Users/lincoln/.nvm/versions/node/v16.14.0/bin/node)
   npm    : 8.3.1
   OS     : macOS Monterey

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by sean-perkins**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
  - Some docs updates need to be made in the `ionic-docs` repo, in a separate PR. See the [contributing guide](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#modifying-documentation) for details.
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

In v7, asynchronously assigning a value to `ion-segment` and `ion-segment-button` can cause the `ion-segment` to render without an active value (segment button does not show as checked). 

Issue URL: resolves #26830

## What is the new behavior?

- The `ion-segment-button` checked state is synced with the parent `ion-segment`, when the component finishes the initial render.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Dev-build: `7.0.0-dev.11678736268.18a0beb1` ✅

### CODE REVIEW

**Comment by sean-perkins** [comment]
Opening this up for review. I identified that calling `updateState()` resolves the problematic behavior in the reproduction (as well as Lincoln has done the same). 

I left this in draft for a bit because I wanted to see if there is an easy way to write tests around this (the reproduction requires a bit of rxjs + Angular). I haven't had the time to do so yet. 

I think the risk of this change is incredibly low (at worst, it is calling `updateState()` when the state is already set correctly). I'd feel comfortable creating a tech debt ticket to track adding test coverage to this in a follow-up sprint, in order to get this into the next RC.

File: core/src/components/segment-button/segment-button.tsx [hunk 1]
```diff
@@ -79,6 +79,10 @@ export class SegmentButton implements ComponentInterface, ButtonInterface {
     };
   }
 
+  componentDidLoad() {
```
Comment (liamdebeasi) [inline core/src/components/segment-button/segment-button.tsx:82]: Threading for discussion:

Are we confident this is a v7 regression? When I triaged this in https://github.com/ionic-team/ionic-framework/issues/26830#issuecomment-1437653626, I was able to reproduce this in v6, but perhaps I reproduced a different issue.

File: core/src/components/segment-button/segment-button.tsx [hunk 2]
```diff
@@ -79,6 +79,10 @@ export class SegmentButton implements ComponentInterface, ButtonInterface {
...
+    this.updateState();
```
Comment (liamdebeasi) [inline core/src/components/segment-button/segment-button.tsx:83]: Why does this work? `this.updateState` is already called in `connectedCallback`, so by the time `componentDidLoad` is called this should already have been run.

File: core/src/components/segment-button/segment-button.tsx (hunk 1 above)
Comment (liamdebeasi) [reply core/src/components/segment-button/segment-button.tsx:82]: Alternatively: Is this a bug that's always been there but is now causing issues because of v7 changes? (possibly the initializeNextTick change?)

File: core/src/components/segment-button/segment-button.tsx [hunk 3]
```diff
@@ -79,6 +79,10 @@ export class SegmentButton implements ComponentInterface, ButtonInterface {
...
+  }
+
```
Comment (liamdebeasi) [inline core/src/components/segment-button/segment-button.tsx:85]: Can you add a test?

File: core/src/components/segment-button/segment-button.tsx (hunk 1 above)
Comment (liamdebeasi) [reply core/src/components/segment-button/segment-button.tsx:82]: Ok I did a bit more digging and this is (fortunately) not an Ionic v7 regression. However, it is much more noticeable now that the `initializeNextTick` config was removed in Ionic v7.

The problem here is that if the `value` property on `ion-segment-button` is set asynchronously, the `updateState` method is not called again.

So given the following:

```html
<ion-segment value="general">
  <ion-segment-button>General</ion-segment-button>
</ion-segment>
```

If you were to asynchronously set the value of the segment button to `"general"`, the segment button would not appear checked.

Below is a test you can use to verify the fix.

<details>
<summary>segment/test/async/segment.e2e.ts</summary>

```typescript
import { expect } from '@playwright/test';
import { test } from '@utils/test/playwright';

test.describe('segment: async', () => {
  test('should set checked state when value is set asynchronously', async ({ page, skip }) => {
    skip.rtl();
    skip.mode('md');

    await page.setContent(`
      <ion-segment value="first">
        <ion-segment-button>First</ion-segment-button>
      </ion-segment>
    `);

    const segmentButton = page.locator('ion-segment-button');

    await segmentButton.evaluate((el: HTMLIonSegmentButtonElement) => el.value = 'first');
    await page.waitForChanges();

    await expect(segmentButton).toHaveClass(/segment-button-checked/);
  });
});

```
</details>

Comment (liamdebeasi) [reply core/src/components/segment-button/segment-button.tsx:82]: If possible, we should merge this into `main` so v6 devs can benefit from this fix too.

**Comment by lincolnthree** [comment]
Thanks so much guys! Really happy you were able to figure out the root cause of what's happening.

**Comment by lincolnthree** [comment]
Just looping back on this. Anything I can do to help? I noticed it didn't make it into v7, and the issue is occurring quite consistently for my application now. Sorry to be a pest! But I've seen a few releases out and this seems so close to the finish line.

**Comment by liamdebeasi** [comment]
We pulled this into the next sprint to take another look at.

**Comment by liamdebeasi** [comment]
@sean-perkins I added the correct fix as well as a test. Mind taking a look when you get a chance? (I changed from an E2E to a unit test too)

**Comment by sean-perkins** [comment]
Looks good to me, I resolved the merge conflict with `main`. I can't review my own PRs, but I'll mark this as merge when ready. 

We can cherry pick the commit into the v6 release branch.

**Review by liamdebeasi — APPROVED** [review]
