### PR TITLE
fix(router-outlet): add ability to active the same component.

### LINKED ISSUE #24653: bug: router-outlet should activate a route with the same components if params are different
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

It is not possible to load a route with the same component in the outlet even if the params are different.

That's because we only [compare the component](https://github.com/ionic-team/ionic-framework/blob/7d5c6afd180b0023de82f621ccab2421e61752ea/core/src/components/router-outlet/route-outlet.tsx#L163-L165), not the params.

### Expected Behavior

It should be possible to load a route with the same component as long as the params are different.

This would be consistent with `<ion-nav>`

### Steps to Reproduce

Activate routes with the same component and different params. 

I'll send a PR with tests.

### Code Reproduction URL

_No response_

### Ionic Info

_No response_

### Additional Information

#24652 needs to be fixed first

### PR DESCRIPTION
**Pull request by vicb**
It it possible to activate the same component as long as parameters are different to match the behavior of <ion-nav>

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [X] Build (`npm run build`) was run locally and any changes were pushed
- [X] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

If 2 routes share the same component and the first is active, the router outlet will not allow activating the second even if the parameters are differents

Issue Number: fixes #24653

## What is the new behavior?

A route route using the same component as the current one can be activated as long as parameters are differents.

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

File: core/src/components/router-outlet/test/basic/e2e.ts [hunk 1]
```diff
@@ -26,4 +26,18 @@ test('getRouteId() should return the route parameters', async () => {
 
   expect(routeId.id).toEqual('PAGE-THREE');
   expect(routeId.params).toEqual({ param: 'route' });
+});
+
+test('is should be possible to activate the same component provided parameters are different', async () => {
```
Comment (sean-perkins) [inline core/src/components/router-outlet/test/basic/e2e.ts:31]:
```suggestion
test('it should be possible to activate the same component provided parameters are different', async () => {
```

**Review by amandaesmith3 — APPROVED** [review]
