### PR TITLE
fix(tabs, tab-bar): use standalone tab bar in React

### LINKED ISSUE #29924: bug: regression: IonRouterOutlet ref is always undefined
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x

### Current Behavior

In ionic 8.2.6, I could get the ref (React) like the following:

```
const ref = useRef();

requestAnimationFrame(() => {
  console.log(ref.current);
});

return <IonRouterOutlet ref={ref} />
```

Which prints:

image

In Ionic 8.3.2, this prints:

image

### Expected Behavior

8.2.6 behavior

### Steps to Reproduce

1. Clone https://github.com/aeharding/bugged-outlet
2. Checkout branch `8.2.6`. Install, `ionic serve`
3. Observe expected output in console
4. Checkout branch `8.3.2`. Install, `ionic serve`
5. Observe bugged output (all `undefined`)

### Code Reproduction URL

https://github.com/aeharding/bugged-outlet

### Ionic Info

```
Ionic:

   Ionic CLI       : 7.2.0 (/Users/aeharding/.nvm/versions/node/v22.1.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 8.3.2

Capacitor:

   Capacitor CLI      : 6.1.2
   @capacitor/android : not installed
   @capacitor/core    : 6.1.2
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v22.1.0 (/Users/aeharding/.nvm/versions/node/v22.1.0/bin/node)
   npm    : 10.7.0
   OS     : macOS Unknown
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by thetaPC**
Issue number: resolves part of #29885, resolves #29924

---------

## What is the current behavior?

React: There are two issues here.

**Issue 1:**

Tab bar could be a standalone element within `IonTabs` and would navigate without issues with a router outlet before v8.3:

```vue
<IonTabs>
  <IonRouterOutlet></IonRouterOutlet>

  <IonTabBar></IonTabBar>
</IonTabs>
```

It would work as if it was written as:

```tsx
<IonTabs>
  <IonRouterOutlet></IonRouterOutlet>

  <IonTabBar slot="bottom">
    <!-- Buttons -->
  </IonTabBar>
</IonTabs>
```

After v8.3, any `ion-tab-bar` that was not a direct child of `ion-tabs` would lose it's expected behavior when used with a router outlet. If a user clicked on a tab button, then the content would not be redirected to that expected view.

**Issue 2:**

Users can no longer add a `ref` to the `IonRouterOutlet`, it always returns undefined.

```
<IonTabs>
      <IonRouterOutlet ref={ref}>

     <IonTabBar slot="bottom">
    <!-- Buttons -->
  </IonTabBar>
</IonTabs>
```

## What is the new behavior?

**Issue 1:**

The React tabs has been updated to pass data to the tab bar through context instead of passing it through a ref. By using a context, the data will be available for the tab bar to use regardless of its level.

**Issue 2:**

Reverted the logic for `routerOutletRef` and added a comment of the importance of it.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Dev build: `8.3.3-dev.11728581904.17739cf7`

How to test **Issue 1**:

1. Create a new React Ionic Framework app (recommended to use Tabs starter)
2. Install deps
3. Move the `IonTabBar` into a separate component
4. Use the new component that holds `IonTabBar`
5. Run project
6. Click on any of the tab buttons
7. Notice that the content and URL does not update
8. Install dev build: `npm install @ionic/react@8.3.3-dev.11728581904.17739cf7`
9. Run project
10. Click on any of the tab buttons
11. Verify that the content and URL updates correctly

How to test **Issue 2**:

1. Clone the issue repo (second link at the top)
2. Install deps
3. Run project
4. Open the browser console
5. Notice that it displays an `undefined`
6. Install the dev build: `npm install @ionic/react@8.3.3-dev.11728581904.17739cf7`
7. Run project
8. Verify that the console log now displays `ion-router-outlet`

### CODE REVIEW

File: packages/react/src/components/navigation/IonTabs.tsx [hunk 1]
```diff
@@ -90,9 +84,32 @@ export const IonTabs = /*@__PURE__*/ (() =>
...
     }
 
+    renderTabsInner(children: React.ReactNode, outlet: React.ReactElement<{}> | undefined) {
+      return (
+        <IonTabsInner {...this.props}>
+          {React.Children.map(children, (child: React.ReactNode) => {
+            if (React.isValidElement(child)) {
+              const isRouterOutlet =
+                child.type === IonRouterOutlet ||
+                (child.type as any).isRouterOutlet ||
```
Comment (BenOsodrac) [inline packages/react/src/components/navigation/IonTabs.tsx:94]: Just an observation, but maybe in these cases is better to use `unknown` than `any`

**Review by BenOsodrac — APPROVED** [review]

File: packages/react/src/components/navigation/IonTabs.tsx (hunk 1 above)
Comment (thetaPC) [reply packages/react/src/components/navigation/IonTabs.tsx:94]: I'll keep that in mind. I recall that we have a ticket to improve the types for this so we can make the update then. Thank you!

**Review by brandyscarney — APPROVED** [review]
Both test cases pass. 👍
