### PR TITLE
fix(react): IonNav apply properties to page components 

### LINKED ISSUE #25602: bug: IonNav in React does not support rootParams
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Using `IonNav` in React does not persist the value of `rootParams` to the components. Any value supplied to `rootParams` will be ignored and the parameters of the component will be `undefined`.

### Expected Behavior

The value of `rootParams` should be applied to the root component. 

### Steps to Reproduce

1. Clone the reproduction: https://github.com/milang/ionic-simplevitejs
2. Checkout `simple-ionnav` branch
3. Install dependencies
4. Run the app in dev mode `npm run dev`
5. Observe that the value supplied as `rootParams` is not detected in the `HelloWorld` component

### Code Reproduction URL

https://github.com/milang/ionic-simplevitejs

### Ionic Info

N/A

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by sean-perkins**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
  - Some docs updates need to be made in the `ionic-docs` repo, in a separate PR. See the [contributing guide](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#modifying-documentation) for details.
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Root params set on `IonNav` are not inherited by the root component.

Issue URL: resolves #25602

## What is the new behavior?

`IonNav` will now assign the properties to the page components correctly.

IonNav now supports two ways to assign properties to page components:

**Memorized Components**

```tsx
const root = useCallback(() => <MyComponent first="Sean" last="Perkins />, []);

<IonNav root={root} />
```

**rootParams**

```tsx
<IonNav root={MyComponent} rootParams={{ first: "Sean", last: "Perkins" }} />
```

Additionally, this PR caches element references, which partially resolves an issue with Vite + React and hmr clearing the views within IonNav. 

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Dev-build: `6.1.15-dev.11657908598.17be2d80`

### CODE REVIEW

**Review by amandaejohnston — APPROVED** [review]
Do we need to update the docs for `rootParams` as well?

**Comment by sean-perkins** [comment]
I have a thought here on how to support both implementation patterns... will report back if it works.

**Comment by sean-perkins** [comment]
Ok this is ready, we can support both memorized components and `rootParams` usages. 🎉

File: packages/react/src/framework-delegate.tsx [hunk 1]
```diff
@@ -1,33 +1,38 @@
...
     const div = document.createElement('div');
     cssClasses && div.classList.add(...cssClasses);
     parentElement.appendChild(div);
 
-    Component = createPortal(component(), div);
+    const componentWithProps = component(propsOrDataObj);
+    const hostComponent = createPortal(componentWithProps, div);
 
-    Component.props = propsOrDataObj;
+    refMap.set(component, hostComponent);
```
Comment (liamdebeasi) [inline packages/react/src/framework-delegate.tsx:25]: Why do we need the map?

Comment (sean-perkins) [reply packages/react/src/framework-delegate.tsx:25]: One instance of the delegate is constructed for one instance of `IonNav`, but `IonNav` can attach multiple views to the DOM. 

The map allows us to keep track of all instances of the individual views that were pushed inside the Nav. We can then do a look-up against the map to find the correct instance to remove the view from the DOM. 

In the previous implementation, the value of `Component` would be reset when a new view was pushed, which prevented the previous view from ever being removed.

Alternatively you could use an object instead of a map here, but since we are associating to a React component, a `WeakMap` would be my recommendation here so that it does not interfere with garbage collection.

**Review by liamdebeasi — APPROVED** [review]
