### PR TITLE
fix(img): draggable attribute is now inherited to inner img element

### LINKED ISSUE #21325: bug: ion-img should accept draggable prop
This basic functionality of html should work as  so we can disable the default drag option for

### PR DESCRIPTION
**Pull request by sean-perkins**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

The `draggable` attribute does not get applied to the inner `img` tag within `ion-img`.

Issue URL: Resolves #21325

## What is the new behavior?

The `draggable` attribute will be reflected to the inner `img` tag within `ion-img`.

- Setting `draggable="true"` will allow the image to be draggable
- Setting `draggable="false"` will disable the image from being draggable.
- Not setting `draggable` will result in the default browser behavior of the image being draggable.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

This PR is in favor of #21686. Co-author credit has been applied to the commit.

### CODE REVIEW

**Review by amandaesmith3 — APPROVED** [review]

**Comment by liamdebeasi** [comment]
I pushed a commit that lets us avoid JSON.parse.

File: core/src/components/back-button/back-button.tsx [hunk 1]
```diff
@@ -24,7 +24,7 @@ import { createColorClasses, hostContext, openURL } from '../../utils/theme';
   shadow: true
 })
 export class BackButton implements ComponentInterface, ButtonInterface {
-  private inheritedAttributes: { [k: string]: any } = {};
+  private inheritedAttributes: Attributes = {};
```
Comment (liamdebeasi) [inline core/src/components/back-button/back-button.tsx:27]: There are several other components that use `{ [k: string]: any }`. Can we either update them all now or update them all in a separate PR?

**Review by liamdebeasi — CHANGES_REQUESTED** [review]

File: core/src/components/back-button/back-button.tsx (hunk 1 above)
Comment (sean-perkins) [reply core/src/components/back-button/back-button.tsx:27]: Updated all the implementations surrounding inheriting attributes with the new type.

**Review by liamdebeasi — APPROVED** [review]
