### PR TITLE
fix(router): fix router push with relative path

### LINKED ISSUE #24718: bug: ion-router push relative navigation is broken
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

The push method of the router is supposed to support relative navigation (i.e `./some/path` and `../some/path`) but the implementation assumes:
- `useHash` = false,
- `root` = /

For example calling `push('./relative')` on `http://localhost:3334/src/components/router/test/basic#/two/three/hello` navigates to `http://localhost:3334/src/components/router/test/basic#/src/components/router/test/relative`.

### Expected Behavior

Calling `push('./relative')` on `http://localhost:3334/src/components/router/test/basic#/two/three/hello` navigates to `http://localhost:3334/src/components/router/test/basic#/two/three/relative`.

### Steps to Reproduce

Call `push()` with a relative when `useHash` is true or `root` is not `/`

### Code Reproduction URL

_No response_

### Ionic Info

bash: ionic: command not found :)

### Additional Information

The problem comes from the fact that there is a confusion between a path and a url.

I have the fix ready and will submit a PR shortly.

### PR DESCRIPTION
**Pull request by vicb**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [X] Build (`npm run build`) was run locally and any changes were pushed - only changes related to this PR
- [X] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Router.push() is buggy when using a relative path and `useHash` = true or `root` != /

Issue Number: fixes #24718 

## What is the new behavior?

Router.push works with relative paths

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

File: core/src/components/router/router.tsx [hunk 1]
```diff
@@ -118,18 +118,19 @@ export class Router implements ComponentInterface {
...
    * @param direction The direction of the animation. Defaults to `"forward"`.
    */
   @Method()
-  async push(url: string, direction: RouterDirection = 'forward', animation?: AnimationBuilder) {
-    if (url.startsWith('.')) {
-      url = (new URL(url, window.location.href)).pathname;
+  async push(path: string, direction: RouterDirection = 'forward', animation?: AnimationBuilder) {
+    if (path.startsWith('.')) {
+      const currentPath = this.previousPath ?? '/';
+      path = (new URL(path, `https://host/${currentPath}`)).pathname;
```
Comment (sean-perkins) [inline core/src/components/router/router.tsx:130]: I'm unfamiliar to this syntax. Can you explain a little of what this does/how this works? Also, would this negatively impact/cause issues with developers who are not serving their content through https?

Comment (vicb) [reply core/src/components/router/router.tsx]: URL [second parameter](https://developer.mozilla.org/en-US/docs/Web/API/URL#usage_notes) is a url but we have a path which is only the path in the router a tree.

So basically we are creating a "fake" url just for the purpose of resolving a relative path. To transform a path to a url, you need to add a protocol (`http(s)://`) and a host (`host`).

We only read back the pathname and the search parts so the protocol and host could be anything, this would change the outcome.

Does this make sense ?

Comment (sean-perkins) [reply core/src/components/router/router.tsx]: Perfect, thanks for the explanation that makes a lot of sense! I think it could be helpful to include an inline comment regarding this.

Comment (vicb) [reply core/src/components/router/router.tsx]: Done

**Review by liamdebeasi — APPROVED** [review]

**Review by amandaesmith3 — APPROVED** [review]
