### PR TITLE
fix(radio-group): enable unselect with spacebar

### LINKED ISSUE #22734: bug: Cannot unselect radio button with space bar with allowEmptySelection true
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

Using an ion-radio-group with allowEmptySelection set to "true", a user is able to unselect via touch and via mouse click, but cannot unselect via spacebar. This causes issues for a11y.

https://ionicframework.com/docs/api/radio-group#properties

**Expected behavior:**
When allowEmptySelection is "true" the user should be able to both select and unselect with a spacebar.
When allowEmptySelection is "false" (or unspecified), the user should only be able to select via spacebar.

**Related code:**

https://github.com/ionic-afl/ionic-v5-observations

### PR DESCRIPTION
**Pull request by willmartindev**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: resolves #22734 

## What is the new behavior?

- Users can now unselect radio buttons with spacebar if `allowEmptySelection` is enabled on the radio group

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: core/src/components/radio-group/radio-group.tsx [hunk 1]
```diff
@@ -144,7 +144,9 @@ export class RadioGroup implements ComponentInterface {
       // space bar on top of a selected radio (only applies
       // to radios in a select popover)
```
Comment (liamdebeasi) [inline core/src/components/radio-group/radio-group.tsx:145]:
```suggestion
      // space bar on top of a selected radio
```

Remove that extra comment since it is no longer true

**Review by liamdebeasi — CHANGES_REQUESTED** [review]
Looks good, but we need to add a test for this before we can merge. I would prefer that we do a spec test if possible since they run a bit faster than E2E tests.

You can add a `radio-group.spec.ts` file in `radio-group/test`. See https://github.com/ionic-team/ionic-framework/blob/next/core/src/components/accordion/test/accordion.spec.ts for examples of how I write the tests. Also see https://stenciljs.com/docs/unit-testing for the Stencil testing API for `newSpecPage`.

We should add a test for when the user presses spacebar on a radio group that has `allowEmptySelection` and a test for when the user presses spacebar on a radio group that does not have `allowEmptySelection`.

File: core/src/components/radio-group/test/radio-group.e2e.ts [hunk 2]
```diff
@@ -0,0 +1,88 @@
...
+    await page.keyboard.press('Space');
+  } else if (selectionMethod === 'mouse') {
+    await page.click(selector);
+  }
+  
+  await page.waitForChanges();
+
+  const radioGroup = await page.find(`ion-radio#${radioButtonId} >>> input`);
+  const checked = await radioGroup.getProperty('checked');
+  return checked;
```
Comment (liamdebeasi) [inline core/src/components/radio-group/test/radio-group.e2e.ts:21]: Any reason why we can't just look at the `checked` property on the host `ion-radio` element instead of diving into the shadow dom?

Comment (liamdebeasi) [reply core/src/components/radio-group/test/radio-group.e2e.ts:21]: Discussed offline to keep test as is. `checked` is a state not a prop.
