### PR TITLE
fix(refresher): force content to be ready before saving the scrollEl

### LINKED ISSUE #22256: bug: ios native refresher refreshes too early when used in modal
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

I use a Refresher within a Modal (iOS Card Style). It behaves not like as i expect, because it doesn't have the native look like the other refreshers. while i would expect the refresher to "show more" as more i pull down, it bugs, and start the refreshing very early.

Also in noticed that the spinner in my project is kind of behind the list (but visible) and only hides if i press or move anything.

**Expected behavior:**

The Refresher should work in a Mode where anywhere else.

**Steps to reproduce:**

I have created a small Repo: https://github.com/EinfachHans/ionic-refresher-bug
It contains the "main" bug, but i can't reproduce the other bug that the spinner is over the list, so i create a small video to help you. Maybe you have an idea or it's related to the same underlaying issue?

**Ionic info:**

```
Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : ios 6.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 24 other plugins)

Utility:

   cordova-res                          : 0.15.1
   native-run (update available: 1.2.1) : 1.0.0

System:

   Android SDK Tools : 25.2.3 (/Users/hanskrywalsky/Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v12.18.3 (/usr/local/bin/node)
   npm               : 6.14.8
   OS                : macOS Catalina
   Xcode             : Xcode 12.0.1 Build version 12A7300
```

### PR DESCRIPTION
**Pull request by EinfachHans**
closes #22256 

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [X] Build (`npm run build`) was run locally and any changes were pushed
- [X] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: #22256 

Like wrote in the linked Issue, the Refresher sometimes starts too early / buggy when used in iOS card style modal. I debugged this today and saw, that the ScrollElement's **offsetHeight** could be zero here:
https://github.com/ionic-team/ionic-framework/blob/c1455a839a25e3e23b7c9e7b7d930055b24c2ecb/core/src/components/refresher/refresher.tsx#L399

This cause the `setupiOSNativeRefresher` to not work properly, as **MAX_PULL** is zero then as well.

## What is the new behavior?

- Before loading the ScrollElement from the Content Element, wait for the Content's Component to be ready

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by liamdebeasi** [comment]
Thanks for the PR. Can you sync your branch with the latest changes in `master`? There were a few changes required for the node 15/npm 7 upgrade which is why outdated branches may see failing tests.

File: core/src/components/refresher/refresher.tsx [hunk 1]
```diff
@@ -396,6 +396,8 @@ export class Refresher implements ComponentInterface {
       return;
     }
 
+    await contentEl.componentOnReady();
```
Comment (liamdebeasi) [inline core/src/components/refresher/refresher.tsx:399]: If we add this here, then we should remove the `componentOnReady` call in https://github.com/ionic-team/ionic-framework/blob/master/core/src/components/refresher/refresher.tsx#L374 as it is redundant.

**Review by liamdebeasi — CHANGES_REQUESTED** [review]

**Comment by EinfachHans** [comment]
@liamdebeasi done

**Comment by liamdebeasi** [comment]
Hmm it looks like it's trying to merge in all of the changes as new commits. It might be easier reset your branch to the latest master, make your change, then force push the updates.

**Comment by EinfachHans** [comment]
oh lol yeah i have seen it^^ did like you said: reset and the force pushed 😊

**Review by liamdebeasi — APPROVED** [review]
Looks good 👍

**Comment by liamdebeasi** [comment]
Merged. Thank you!
