### PR TITLE
fix(react): add onPointerDown, onTouchEnd, add onTouchMove

### LINKED ISSUE #29174: bug: IonTabButton doesn't have default HTML event attributes typed
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

IonTabButton is missing regular HTML types (onPointerDown, onTouchEnd, onTouchMove, etc)

### Expected Behavior

Should have proper types.

### Steps to Reproduce

Try to add `onPointerDown` to `IonTabButton` in React. Typescript will complain, but the touch end handler will be properly connected/called.

### Code Reproduction URL

https://stackblitz.com/edit/wl7fhb-xaawyq?file=src%2Fmain.tsx

### Ionic Info

N/A - stackblitz

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Stev24**
Issue number: resolves #29174

---------

## What is the current behavior?

React throws tab errors with `IonTabButton` when binding to `onPointerDown`, `onTouchEnd` and `onTouchMove`

## What is the new behavior?

- Adds missing type definitions for `onPointerDown`, `onTouchEnd` and `onTouchMove` to `IonTaButton`
- React does not throw type errors when binding callback functions to these events

---------

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: packages/react/src/components/navigation/IonTabButton.tsx [hunk 1]
```diff
@@ -40,8 +43,16 @@ export const IonTabButton = /*@__PURE__*/ (() =>
        * component would result in duplicate handler calls.
        */
       // eslint-disable-next-line @typescript-eslint/no-unused-vars
-      const { onClick, ...rest } = this.props;
-      return <IonTabButtonInner onIonTabButtonClick={this.handleIonTabButtonClick} {...rest}></IonTabButtonInner>;
+      const { onClick, onPointerDown, onTouchEnd, onTouchMove, ...rest } = this.props;
+      return (
+        <IonTabButtonInner
+          onIonTabButtonClick={this.handleIonTabButtonClick}
+          onPointerDown={onPointerDown}
```
Comment (sean-perkins) [inline packages/react/src/components/navigation/IonTabButton.tsx:50]: Is manually binding the properties necessary here? The spread operator for the rest of the properties should handle this detail. 

I believe the original issue is the lack of types causing errors when developers try to bind to the `onPointerDown`, etc. events. That should be resolved by your changes on L13-15.

Comment (Stev24) [reply packages/react/src/components/navigation/IonTabButton.tsx]: @sean-perkins properties were removed

**Review by thetaPC — APPROVED** [review]
LGTM, thank you!
