### PR TITLE
fix(vue): components have correct name in Vue Dev Tools

### LINKED ISSUE #25199: bug: Ionic Vue components show as Anonymous Component in Vue 3 Dev tools
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Vue developers using the Vue 3 Dev tools will see "Anonymous Component" in place of all generated Vue wrappers.

Screen Shot 2022-04-26 at 2 08 10 PM

### Expected Behavior

The component name should display instead.

### Steps to Reproduce

1. Install Vue 3 Dev Tools Chrome extension
2. Open Ionic Vue app
3. Open dev tools
4. Jump to Vue dev tools
5. See that Ionic components display as "Anonymous Component"

### Code Reproduction URL

_No response_

### Ionic Info

N/A

### Additional Information

This is a two part issue:
1. The output targets repo is generating the proxies incorrectly
2. The custom maintained proxies (routing components) are also generating incorrectly

Will open a PR shortly for both.

### PR DESCRIPTION
**Pull request by liamdebeasi**
## What is the current behavior?

Issue URL: resolves #25199

Vue components show up as "Anonymous Component" in Vue Dev Tools. This is caused by our use of `displayName` instead of `name`. This required a fix in the Vue Output Target package. See https://github.com/ionic-team/stencil-ds-output-targets/pull/257 for more info.

## What is the new behavior?

- Updates the Vue Output Target dependency
- Functional components created manually in Ionic Vue now set `name` instead of `displayName`. Note: Non-functional components were never impacted by this bug.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Dev build: `7.0.2-dev.11681308435.141a05de`

### CODE REVIEW

File: packages/vue/src/components/IonApp.ts [hunk 1]
```diff
@@ -16,6 +16,8 @@ export const IonApp = /*@__PURE__*/ defineComponent((_, { attrs, slots }) => {
   };
 });
 
+IonApp.name = "IonApp";
```
Comment (amandaejohnston) [inline packages/vue/src/components/IonApp.ts:19]: I noticed that other components set the `name` as part of the initial `defineComponent` call: https://github.com/ionic-team/ionic-framework/blob/main/packages/vue/src/components/IonPage.ts#L4 Is it possible to do that here, or is there a blocking difference in how the components are set up? I'm just wary of this line being missed if we have to copy-paste this setup in the future. (Ditto for `IonBackButton` and `IonNav`)

Comment (amandaejohnston) [reply packages/vue/src/components/IonApp.ts:19]: Gotcha, thanks 👍

**Review by amandaejohnston — APPROVED** [review]
