### PR TITLE
fix(input): blur and then focus the input for safari

### LINKED ISSUE #21509: bug: ion-item padding prevents child ion-input focus
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

While working with a community member, it was observed that when a floating label and `ion-input` are nested in an `ion-item`, users can tap the left padding of the item and it will:

1. Animate the floating label to the top
2. Present the device keyboard
3. *Not* focus the input field

This behavior was captured for iOS with Ionic Angular 5.2.0.

**Expected behavior:**

When tapping the padding, it should place the input field in focus in addition to the other actions performed.

**Steps to reproduce:**

1. Create an `ion-item` with an `ion-label` and `ion-input` as children.
2. Set the `position` of the `ion-label` to `floating`.
3. Open the app on an iOS device/simulator.
4. Tap the far-left of the `ion-item`.

Please find a GIF of this behavior towards the bottom of this Issue.

**Related code:**

Reproduction Application: https://github.com/ehorodyski-ionic/ionic-floating-label-focus-issue

**Other information:**

ezgif-1-05eaea0df48e

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.10.0 
   Ionic Framework               : @ionic/angular 5.2.0
   @angular-devkit/build-angular : 0.901.8
   @angular-devkit/schematics    : 9.1.8
   @angular/cli                  : 9.1.8
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.2.0
   @capacitor/core : 2.2.0

Utility:

   cordova-res (update available: 0.14.0) : 0.11.0
   native-run                             : 1.0.0

System:

   NodeJS : v12.16.1 (/usr/local/bin/node)
   npm    : 6.14.4
   OS     : macOS Catalina
```

### PR DESCRIPTION
**Pull request by brandyscarney**
:warning: NEW dev build `5.4.0-dev.202008212054.e0116be` :warning:

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

When clicking on the padding of an item, the keyboard displays in Safari but it does not focus the proper input due to delegatesFocus not working properly.

Related WebKit bug: https://bugs.webkit.org/show_bug.cgi?id=214859

Issue Number: fixes #21509

## What is the new behavior?

This change essentially blurs & then focuses the native input to make it work in Safari.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: core/src/components/input/input.tsx [hunk 1]
```diff
@@ -23,6 +23,16 @@ export class Input implements ComponentInterface {
   private didBlurAfterEdit = false;
   private tabindex?: string | number;
 
+  /**
+   * This is required for a WebKit bug which requires us to
+   * blur and focus and input to properly focus the input in
```
Comment (brandyscarney) [inline core/src/components/input/input.tsx:28]:
```suggestion
   * blur and focus an input to properly focus the input in
```
