### PR TITLE
fix(labels): prevent clicking a label from triggering onClick twice on several components

### LINKED ISSUE #30165: bug: clicking within ion-input on the label triggers (click) twice
### Prerequisites

- [x] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [x] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [x] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x

### Current Behavior

When you click on an ion-input with attribute (click)="function", this function is called twice when you click on the label within that ion-input. When you click on the value it is called once (as it should).

### Expected Behavior

That the function would only be called once when you click on the label within the ion-input

### Steps to Reproduce

[Stackblitz](https://stackblitz.com/edit/ubs56gug?file=src%2Fapp%2Fexample.component.html)

1. Recent ionic & angular
2. Example: 
```
<ion-list>
  <ion-item>
    <ion-input label="Input with value" value="121 S Pinckney St #300" (click)="clicked()"></ion-input>
  </ion-item>

  <ion-item>
    <ion-input labelPlacement="floating" label="Input with value" value="121 S Pinckney St #300" (click)="clicked()"></ion-input>
  </ion-item>
</ion-list>
```
3. Clicking on the label within the ion-input calls the function clicked() twice.

### Code Reproduction URL

https://stackblitz.com/edit/ubs56gug?file=src%2Fapp%2Fexample.component.html

### Ionic Info

Its ionic from the current stackblitz config used in the docs, from package.json:
```
"@angular/animations": "^19.0.0",
    "@angular/common": "^19.0.0",
    "@angular/compiler": "^19.0.0",
    "@angular/core": "^19.0.0",
    "@angular/forms": "^19.0.0",
    "@angular/platform-browser": "^19.0.0",
    "@angular/platform-browser-dynamic": "^19.0.0",
    "@angular/router": "^19.0.0",
    "@ionic/angular": "^8.0.0",
    "@ionic/core": "^8.0.0",
    "ionicons": "7.4.0",
    "rxjs": "^7.8.1",
    "tslib": "^2.5.0",
    "zone.js": "~0.15.0"
```

### Additional Information

Adding event.preventDefault();  can be used as a dirty fix untill this issue gets resolved.

### PR DESCRIPTION
**Pull request by ShaneK**
Issue number: resolves #30165

---------

## What is the current behavior?

Currently, several components will trigger their `onClick` twice if you click on their labels.

## What is the new behavior?

After this fix, the affected components will only trigger `onClick` once per click of their labels or click directly on the element.

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

The affected components are:
- Checkbox
- Select
- Textarea
- Toggle
- Input

I also tested radio and range but could not reproduce the issue for them.

Note that two of the components, checkbox and toggle, had to have special implementations for both their test and fix because of how the host component acts as the component for accessibility purposes.

Current dev build: `8.5.7-dev.11746044124.147aab6c`

### CODE REVIEW

File: core/src/components/toggle/toggle.tsx
Comment (thetaPC) [inline core/src/components/toggle/toggle.tsx:1]: I'm unable to replicate the original issue with toggle when clicking on the wrapper even through the console. Where exactly should I be clicking?

File: core/src/components/input/test/basic/input.e2e.ts [hunk 1]
```diff
@@ -130,4 +130,72 @@ configs({ modes: ['ios'], directions: ['ltr'] }).forEach(({ title, screenshot, c
...
+
+      // Verify the click was triggered exactly once
+      expect(clickEvent).toHaveReceivedEventTimes(1);
+
+      // Verify that the event target is the checkbox and not the item
+      const event = clickEvent.events[0];
+      expect((event.target as HTMLElement).tagName.toLowerCase()).toBe('ion-input');
+    });
+
+    test('should trigger onclick only once when clicking the wrapper', async ({ page }) => {
```
Comment (thetaPC) [inline core/src/components/input/test/basic/input.e2e.ts:168]: This test passes when I remove the changes to `input.tsx` and I'm also unable to reproduce the double click with the wrapper.

File: core/src/components/select/test/basic/select.e2e.ts [hunk 2]
```diff
@@ -150,6 +150,41 @@ configs({ modes: ['ios'], directions: ['ltr'] }).forEach(({ title, config }) =>
       expect(alerts.length).toBe(1);
     });
   });
+
+  test.describe(title('select: click'), () => {
+    test('clicking a select label should only trigger onclick once', async ({ page }) => {
+      // Create a spy function in page context
```
Comment (thetaPC) [inline core/src/components/select/test/basic/select.e2e.ts:156]:
```suggestion
      testInfo.annotations.push({
        type: 'issue',
        description: 'https://github.com/ionic-team/ionic-framework/issues/30165',
      });
      // Create a spy function in page context
```

File: core/src/components/input/test/basic/input.e2e.ts [hunk 3]
```diff
@@ -130,4 +130,72 @@ configs({ modes: ['ios'], directions: ['ltr'] }).forEach(({ title, screenshot, c
       await expect(item).toHaveScreenshot(screenshot(`input-with-clear-button-item-color`));
     });
   });
+
+  test.describe(title('input: click'), () => {
+    test('should trigger onclick only once when clicking the label', async ({ page }) => {
+      // Create a spy function in page context
```
Comment (thetaPC) [inline core/src/components/input/test/basic/input.e2e.ts:136]:
```suggestion
      testInfo.annotations.push({
        type: 'issue',
        description: 'https://github.com/ionic-team/ionic-framework/issues/30165',
      });
      // Create a spy function in page context
```

File: core/src/components/textarea/test/basic/textarea.e2e.ts [hunk 4]
```diff
@@ -0,0 +1,31 @@
+import { expect } from '@playwright/test';
+import { configs, test } from '@utils/test/playwright';
+
+configs({ modes: ['ios'], directions: ['ltr'] }).forEach(({ title, config }) => {
+  test.describe(title('textarea: click'), () => {
+    test('should trigger onclick only once when clicking the label', async ({ page }) => {
+      // Create a spy function in page context
```
Comment (thetaPC) [inline core/src/components/textarea/test/basic/textarea.e2e.ts:7]:
```suggestion
      testInfo.annotations.push({
        type: 'issue',
        description: 'https://github.com/ionic-team/ionic-framework/issues/30165',
      });
      // Create a spy function in page context
```

File: core/src/components/checkbox/checkbox.tsx
[the remark this answers is not in the document]
Comment (ShaneK) [reply core/src/components/checkbox/checkbox.tsx:1]: All of these should be the label, not the wrapper, causing the issue. The input had one extra special issue addressed caused by clicking the wrapper.

File: core/src/components/toggle/toggle.tsx
Comment (ShaneK) [reply core/src/components/toggle/toggle.tsx:1]: All of these should be the label, not the wrapper, causing the issue. The input had one extra special issue addressed caused by clicking the wrapper.

File: core/src/components/input/test/basic/input.e2e.ts (hunk 1 above)
Comment (ShaneK) [reply core/src/components/input/test/basic/input.e2e.ts]: Just pushed a fix for that, I accidentally removed the `label-placement` property, which kinda helps cause the issue. Good catch.

File: core/src/components/toggle/test/basic/toggle.e2e.ts [hunk 5]
```diff
@@ -0,0 +1,33 @@
+import { expect } from '@playwright/test';
+import { configs, test } from '@utils/test/playwright';
+
+configs({ modes: ['ios'], directions: ['ltr'] }).forEach(({ title, config }) => {
+  test.describe(title('toggle: click'), () => {
+    test('should trigger onclick only once when clicking the label', async ({ page }) => {
+      // Create a spy function in page context
```
Comment (thetaPC) [inline core/src/components/toggle/test/basic/toggle.e2e.ts:7]:
```suggestion
      testInfo.annotations.push({
        type: 'issue',
        description: 'https://github.com/ionic-team/ionic-framework/issues/30165',
      });
      // Create a spy function in page context
```

File: core/src/components/checkbox/test/basic/checkbox.e2e.ts [hunk 6]
```diff
@@ -99,4 +99,33 @@ configs({ modes: ['ios'], directions: ['ltr'] }).forEach(({ title, config }) =>
       expect(ionChange).not.toHaveReceivedEvent();
     });
   });
+
+  test.describe(title('checkbox: click'), () => {
+    test('clicking a checkbox label should only trigger onclick once', async ({ page }) => {
+      // Create a spy function in page context
```
Comment (thetaPC) [inline core/src/components/checkbox/test/basic/checkbox.e2e.ts:105]:
```suggestion
      testInfo.annotations.push({
        type: 'issue',
        description: 'https://github.com/ionic-team/ionic-framework/issues/30165',
      });
      // Create a spy function in page context
```

**Review by thetaPC — APPROVED** [review]
LGTM, just missing two annotations but not blockers to move to testing

File: core/src/components/checkbox/test/basic/checkbox.e2e.ts (hunk 6 above)
Comment (ShaneK) [reply core/src/components/checkbox/test/basic/checkbox.e2e.ts:110]: Done manually so I could include testInfo, thanks!

File: core/src/components/toggle/test/basic/toggle.e2e.ts (hunk 5 above)
Comment (ShaneK) [reply core/src/components/toggle/test/basic/toggle.e2e.ts:12]: Done manually so I could include testInfo, thanks!

File: core/src/components/checkbox/test/basic/checkbox.e2e.ts [hunk 7]
```diff
@@ -99,4 +99,38 @@ configs({ modes: ['ios'], directions: ['ltr'] }).forEach(({ title, config }) =>
       expect(ionChange).not.toHaveReceivedEvent();
     });
   });
+
+  test.describe(title('checkbox: click'), () => {
+    test('clicking a checkbox label should only trigger onclick once', async ({ page }, testInfo) => {
```
Comment (brandyscarney) [inline core/src/components/checkbox/test/basic/checkbox.e2e.ts:104]:
```suggestion
    test('should trigger onclick only once when clicking the label', async ({ page }, testInfo) => {
```

For consistency with the other tests

File: core/src/components/select/test/basic/select.e2e.ts [hunk 8]
```diff
@@ -150,6 +150,45 @@ configs({ modes: ['ios'], directions: ['ltr'] }).forEach(({ title, config }) =>
       expect(alerts.length).toBe(1);
     });
   });
+
+  test.describe(title('select: click'), () => {
+    test('clicking a select label should only trigger onclick once', async ({ page }, testInfo) => {
```
Comment (brandyscarney) [inline core/src/components/select/test/basic/select.e2e.ts:155]:
```suggestion
    test('should trigger onclick only once when clicking the label', async ({ page }, testInfo) => {
```

For consistency with the other tests

**Review by brandyscarney — APPROVED** [review]
Tested the click events locally, including inside of an `ion-item` and verified all click events fire once now. Also verified the e2e tests fail without the fixes. Suggested a change to a couple test names for consistency. Looks good though! Great work. 🚀
