### PR TITLE
fix(react/vue): properly switch ionicon based on the mode when ios/md is set

### LINKED ISSUE #26207: bug: Ionicon does not properly switch icons based on the mode in React & Vue
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Setting the `ios` and `md` properties on `<ion-icon>` in Vue and React is not switching between them properly when setting the mode in the global config. 

### Expected Behavior

The `ion-icon` should respect the global config and switch the icon based on the mode. 

### Steps to Reproduce

Using the following markup:

## Vue

```html
<ion-icon slot="icon-only" :ios="star" :md="heart"></ion-icon>
```

and setting the config globally:

```typescript
createApp(App).use(IonicVue, {
  mode: 'ios'
}).mount('#app');
```

##  React:

```tsx
<IonIcon slot="icon-only" ios={star} md={heart}></IonIcon>
```

and setting the config globally:

```tsx
setupIonicReact({
  mode: 'ios',
});
```

## Results

If you switch the mode above in either example from `ios` to `md` you'll see the icon being displayed is always the `heart`.

It seems that the icon switches based on the platform as emulating ios does work to change the icon. 

### Code Reproduction URL

https://stackblitz.com/edit/angular-rduzd8?file=src%2Fcomponents%2FExample.vue,src%2Fmain.ts

### Ionic Info

```
Ionic:

   Ionic CLI       : 6.20.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 6.3.3

Capacitor:

   Capacitor CLI      : 4.4.0
   @capacitor/android : not installed
   @capacitor/core    : 4.4.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.1

System:

   NodeJS : v16.17.0 (/usr/local/bin/node)
   npm    : 8.15.0
   OS     : macOS Monterey
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by brandyscarney**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
  - Some docs updates need to be made in the `ionic-docs` repo, in a separate PR. See the [contributing guide](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#modifying-documentation) for details.
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Setting the `ios` and `md` properties on `<ion-icon>` in Vue and React is not switching between them properly when setting the mode in the global config or as a property on `<ion-icon>`.

Issue URL: closes #26207

## What is the new behavior?

The icon behavior when `ios` or `md` is defined on `<ion-icon>` for Vue/React has changed to:
- If the `<ion-icon>` has `mode` defined as in `<ion-icon mode="ios" :ios="star" :md="heart">` (Vue syntax) then the icon will always show the `star` as that is the value of`ios`  
- If the global mode is set either via the global config or through the url (`?ionic:mode=ios`) then the icon used should be for that mode
- If no mode is set, use the icon for the mode that is set by default based on the platform 
- Fallback to `md` if no mode or platform matches

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

#### Passing

1. Run `npm i` and `npm run build` from `core`
1. Run `npm i` and `npm run build` from `packages/vue`
1. Run `npm i` and `npm run build` from `packages/vue-router`
1. Run `./build.sh vue3` from `packages/vue/test`
1. `cd build/vue3/` and run `npm i` and then `npm run sync`
1. Run `npm run test:e2e`
1. Verify that the icons test passes 

#### Failing

1. Run `./build.sh vue3` from `packages/vue/test`
1. `cd build/vue3/` and run `npm run test:e2e` (do NOT run sync)
1. Verify that the icons test fails on ios
  Screenshot 2023-03-14 at 11 48 28 AM

#### Passing

1. Run `npm i` and `npm run build` from `core`
1. Run `npm i` and `npm run build` from `packages/react`
1. Run `npm i` and `npm run build` from `packages/react-router`
1. `cd react/test-app` and run `npm i` and then `npm run sync`
1. Run `npm run build` and then `npm run e2e`
1. Verify that the icons test passes

#### Failing

1. Go into `packages/react/src/components/IonIcon.tsx` and change line 45 back to:
    ```
    if (isPlatform('ios')) {
    ```
    and then add its import back:
    ```
    import { createForwardRef, isPlatform } from './utils';
    ```
    Comment out the now unused config code, then run the following in `packages/react`:
    ```bash
    npm run build
    ```
1. In the test-app run:
    ```bash
    npm run sync
    npm run build
    npm run e2e
    ```
1. Verify the icons test now fails on ios
  Screenshot 2023-03-14 at 2 50 52 PM

### CODE REVIEW

**Review by amandaejohnston — APPROVED** [review]

File: packages/vue/src/components/IonIcon.ts [hunk 1]
```diff
@@ -19,11 +20,15 @@ export const IonIcon = /*@__PURE__*/ defineComponent({
   setup(props, { slots }) {
     defineCustomElement();
     return () => {
-      const { icon, ios, md } = props;
+      const { icon, ios, md, mode } = props;
 
       let iconToUse: typeof icon;
+
+      const config = getConfig();
```
Comment (liamdebeasi) [inline packages/vue/src/components/IonIcon.ts:27]: `getConfig` can return null, so we should have a fallback for when that is the case: https://github.com/ionic-team/ionic-framework/blob/27a5356fa2b72073d565e9d6f527107869faa3ee/packages/vue/src/utils.ts#L66

File: packages/react/src/components/IonIcon.tsx [hunk 2]
```diff
@@ -34,12 +34,15 @@ class IonIconContainer extends React.PureComponent<InternalProps> {
   }
 
   render() {
-    const { icon, ios, md, ...rest } = this.props;
+    const { icon, ios, md, mode, ...rest } = this.props;
 
     let iconToUse: typeof icon;
 
+    const config = getConfig();
```
Comment (liamdebeasi) [inline packages/react/src/components/IonIcon.tsx:41]: `getConfig` can return null so we should have a fallback for when that is the case: https://github.com/ionic-team/ionic-framework/blob/27a5356fa2b72073d565e9d6f527107869faa3ee/packages/react/src/components/utils/index.tsx#L31

**Review by liamdebeasi — CHANGES_REQUESTED** [review]
Can we write tests to verify this behavior in the react and vue packages?

**Review by liamdebeasi — APPROVED** [review]
